build:
  verbosity: minimal
  
build_script :
 - '%BASH_PATH% -lc "echo $PATH ; which g++"'
 - '%BASH_PATH% -lc "cd $APPVEYOR_BUILD_FOLDER; autoreconf -vfi && ./configure --prefix=$(pwd)/usr/local/ --enable-nolto --enable-mingw-native && make && make install "'
 - '%BASH_PATH% -lc "cd $APPVEYOR_BUILD_FOLDER; 7z a -tzip windows.zip usr/ "'


environment :
 MSYSTEM: MINGW64 
 BASH_PATH: C:\msys64\usr\bin\bash


artifacts:
  - path: windows.zip
    name: windows.zip
  
