DDD: AdditiveMap< K, V, EqualKey > Class Template Reference
AdditiveMap< K, V, EqualKey > Class Template Reference
#include <AdditiveMap.hpp>
Public Types
typedef mapType::value_type value_type
typedef mapType::const_iterator const_iterator
typedef mapType::iterator iterator
Public Member Functions
AdditiveMap ()
const_iterator end () const
const_iterator begin () const
iterator find (const K &key)
int addAll (const AdditiveMap< K, V > &other)
int addAll (const_iterator begin, const_iterator end)
bool add (const K &key, const V &value)
bool remove (const K &key, const V &value)
Private Types
typedef std::vector< std::pair< K, V > > mapType
Private Attributes
mapType map
Member Typedef Documentation
const_iterator
template<typename K , typename V , typename EqualKey = d3::util::equal<K>> typedef mapType::const_iterator AdditiveMap< K, V, EqualKey >::const_iterator
iterator
template<typename K , typename V , typename EqualKey = d3::util::equal<K>> typedef mapType::iterator AdditiveMap< K, V, EqualKey >::iterator
mapType
template<typename K , typename V , typename EqualKey = d3::util::equal<K>> typedef std::vector<std::pair<K,V> > AdditiveMap< K, V, EqualKey >::mapType private
value_type
template<typename K , typename V , typename EqualKey = d3::util::equal<K>> typedef mapType::value_type AdditiveMap< K, V, EqualKey >::value_type
Constructor & Destructor Documentation
AdditiveMap()
template<typename K , typename V , typename EqualKey = d3::util::equal<K>> AdditiveMap< K, V, EqualKey >::AdditiveMap () inline
Member Function Documentation
add()
template<typename K , typename V , typename EqualKey = d3::util::equal<K>> bool AdditiveMap< K, V, EqualKey >::add (const K & key, const V & value) inline
References AdditiveMap< K, V, EqualKey >::find(), and AdditiveMap< K, V, EqualKey >::map.
Referenced by AdditiveMap< K, V, EqualKey >::addAll(), StrongMLHom::eval(), nsMLHom::Identity::eval(), nsMLHom::GHomAdapter::eval(), nsMLHom::ConstantUp::eval(), nsMLHom::LeftConcat::eval(), StrongMLShom::eval(), nsMLShom::Identity::eval(), nsMLShom::GShomAdapter::eval(), nsMLShom::ConstantUp::eval(), and nsMLShom::LeftConcat::eval().
addAll() [1/2]
template<typename K , typename V , typename EqualKey = d3::util::equal<K>> int AdditiveMap< K, V, EqualKey >::addAll (const AdditiveMap< K, V > & other) inline
References AdditiveMap< K, V, EqualKey >::addAll(), AdditiveMap< K, V, EqualKey >::begin(), and AdditiveMap< K, V, EqualKey >::end().
Referenced by AdditiveMap< K, V, EqualKey >::addAll(), nsMLHom::Add::eval(), and nsMLShom::Add::eval().
addAll() [2/2]
template<typename K , typename V , typename EqualKey = d3::util::equal<K>> int AdditiveMap< K, V, EqualKey >::addAll (const_iterator begin, const_iterator end) inline
References AdditiveMap< K, V, EqualKey >::add(), AdditiveMap< K, V, EqualKey >::begin(), and AdditiveMap< K, V, EqualKey >::end().
begin()
template<typename K , typename V , typename EqualKey = d3::util::equal<K>> const_iterator AdditiveMap< K, V, EqualKey >::begin () const inline
References AdditiveMap< K, V, EqualKey >::map.
Referenced by AdditiveMap< K, V, EqualKey >::addAll(), AdditiveMap< K, V, EqualKey >::addAll(), StrongMLHom::eval(), MLHomAdapter::eval(), nsMLHom::ConstantUp::eval(), nsMLHom::LeftConcat::eval(), StrongMLShom::eval(), nsMLShom::ConstantUp::eval(), nsMLShom::LeftConcat::eval(), and sns::MLShomAdapter::eval().
end()
template<typename K , typename V , typename EqualKey = d3::util::equal<K>> const_iterator AdditiveMap< K, V, EqualKey >::end () const inline
References AdditiveMap< K, V, EqualKey >::map.
Referenced by AdditiveMap< K, V, EqualKey >::addAll(), AdditiveMap< K, V, EqualKey >::addAll(), StrongMLHom::eval(), MLHomAdapter::eval(), nsMLHom::ConstantUp::eval(), nsMLHom::LeftConcat::eval(), StrongMLShom::eval(), nsMLShom::ConstantUp::eval(), nsMLShom::LeftConcat::eval(), and sns::MLShomAdapter::eval().
find()
template<typename K , typename V , typename EqualKey = d3::util::equal<K>> iterator AdditiveMap< K, V, EqualKey >::find (const K & key) inline
References AdditiveMap< K, V, EqualKey >::map.
Referenced by AdditiveMap< K, V, EqualKey >::add(), and AdditiveMap< K, V, EqualKey >::remove().
remove()
template<typename K , typename V , typename EqualKey = d3::util::equal<K>> bool AdditiveMap< K, V, EqualKey >::remove (const K & key, const V & value) inline
References AdditiveMap< K, V, EqualKey >::find(), and AdditiveMap< K, V, EqualKey >::map.
Member Data Documentation
map
template<typename K , typename V , typename EqualKey = d3::util::equal<K>> mapType AdditiveMap< K, V, EqualKey >::map private
Referenced by AdditiveMap< K, V, EqualKey >::add(), AdditiveMap< K, V, EqualKey >::begin(), AdditiveMap< K, V, EqualKey >::end(), AdditiveMap< K, V, EqualKey >::find(), and AdditiveMap< K, V, EqualKey >::remove().
The documentation for this class was generated from the following file:
AdditiveMap.hpp
Please comment this page and report errors about it on the RefDocComments page.