DDD: _DED_Add Class Reference
_DED_Add Class Reference
Public Member Functions
size_t hash () const
bool operator== (const _DED &e) const
_DED * clone () const
GDDD eval () const
~_DED_Add ()
Static Public Member Functions
static GDDD create (const std::set< GDDD > &d)
Public Attributes
GDDD result
Private Member Functions
_DED_Add (const std::set< GDDD > &d)
Private Attributes
std::vector< GDDD > parameters
Constructor & Destructor Documentation
_DED_Add()
_DED_Add::_DED_Add (const std::set< GDDD > & d) inline private
Referenced by clone(), and create().
~_DED_Add()
_DED_Add::~_DED_Add () inline
Member Function Documentation
clone()
_DED* _DED_Add::clone () const inline virtual
Implements _DED.
References _DED_Add().
create()
GDDD _DED_Add::create (const std::set< GDDD > & d) static
References _DED_Add(), compute(), GDDD::null, GDDD::one, parameters, and GDDD::top.
Referenced by DED::add().
eval()
GDDD _DED_Add::eval () const virtual
Implements _DED.
References DED::add(), and parameters.
hash()
size_t _DED_Add::hash () const virtual
Implements _DED.
References parameters.
operator==()
bool _DED_Add::operator== (const _DED & e) const virtual
Implements _DED.
References parameters.
Member Data Documentation
parameters
std::vector<GDDD> _DED_Add::parameters private
Referenced by create(), eval(), hash(), and operator==().
result
GDDD _DED::result inherited
The documentation for this class was generated from the following file:
DED.cpp
Please comment this page and report errors about it on the RefDocComments page.