DDD: StrongHom Class Reference
StrongHom Class Reference abstract
The abstract base class for user defined operations.
#include <Hom.h>
Public Member Functions
StrongHom ()
Default constructor.
virtual ~StrongHom ()
Default destructor.
virtual GDDD phiOne () const
Evaluation over terminal GDDD::one.
virtual GHom phi (int var, int val) const =0
Evaluation over an arbitrary arc of a SDD.
virtual bool operator== (const StrongHom &h) const =0
Comparator is pure virtual. Define a behavior in user homomorphisms.
bool operator== (const _GHom &h) const
Comparator for unicity table.
virtual void print (std::ostream &os) const
pretty print
GDDD eval (const GDDD &) const
The evaluation mechanism of strong homomorphisms.
virtual GDDD has_image (const GDDD &) const
GDDD has_image_skip (const GDDD &) const
virtual bool skip_variable (int) const
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
virtual bool is_selector () const
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
virtual const GHom::range_t get_range () const
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
virtual GHom invert (const GDDD &) const
returns the predescessor homomorphism, using pot to determine variable domains
bool operator< (const _GHom &h) const
Ordering between _GHom. It is the chronological ordering of creation.
virtual size_t hash () const =0
Hash key computation.
virtual _GHom * clone () const =0
virtual void mark () const
For garbage collection. Used in first phase of garbage collection.
virtual GHom negate () const
returns a negation of a selector homomorphism h, such that h.negate() (d) = d - h(d)
virtual GHom compose (const GHom &r) const
Static Public Member Functions
static const _GHom * get_concret (const GHom &ghom)
Private Member Functions
GDDD eval_skip (const GDDD &) const
Private Attributes
int refCounter
For garbage collection.
bool marking
For garbage collection.
bool immediat
For operation cache management.
size_t creation_counter
Counter of objects created (see constructors).
Detailed Description
The abstract base class for user defined operations.
This is the class users should derive their operations from. It defines the interface of a Strong Homomorphism :
evaluation over terminal GDDD::one, which should return a constant DDD
evaluation over an arbitrary var–val--> pair, that returns a homomorphism to apply to the successor node Users also have to provide a comparison function, and a hash function (from _GHom). See the demo folder for examples of user defined homomorphisms.
Constructor & Destructor Documentation
StrongHom()
StrongHom::StrongHom () inline
Default constructor.
Empty behavior.
Todo:
Is this declaration useful ?
~StrongHom()
virtual StrongHom::~StrongHom () inline virtual
Default destructor.
Empty behavior.
Todo:
Is this declaration useful ?
Member Function Documentation
clone()
virtual _GHom * _GHom::clone () const pure virtual inherited
Implemented in Identity, Constant, Apply2k, DomExtract, Mult, Inter, NotCond, Add, Monotonic, Compose, And, LeftConcat, RightConcat, Minus, Fixpoint, MLHomAdapter, _VarCompState, _setVarConst, _incVar, and _VarCompVar.
compose()
GHom _GHom::compose (const GHom & r) const virtual inherited
Reimplemented in _VarCompState, and _VarCompVar.
References GHom::id, and GDDD::null.
Referenced by _VarCompState::compose(), _VarCompVar::compose(), and GHom::compose().
eval()
GDDD StrongHom::eval (const GDDD & d) const virtual
The evaluation mechanism of strong homomorphisms.
Evaluation is defined as :
Let an SDD d= (var, Union_i (val_i, d_i))
h (d) = Sum_i (phi(var, val_i) (d_i))
Implements _GHom.
References DED::add(), GDDD::begin(), GDDD::end(), GDDD::null, GDDD::one, phi(), phiOne(), GDDD::top, and GDDD::variable().
eval_skip()
GDDD _GHom::eval_skip (const GDDD & d) const private inherited
References GDDD::begin(), GDDD::end(), _GHom::eval(), GHom::id, GDDD::null, GDDD::one, _GHom::skip_variable(), GDDD::top, and GDDD::variable().
Referenced by GHom::eval().
get_concret()
static const _GHom * _GHom::get_concret (const GHom & ghom) inline static inherited
References GHom::concret.
Referenced by Add::Add(), addCompositionParameter(), _VarCompState::compose(), _VarCompVar::compose(), And::eval(), Fixpoint::eval(), Fixpoint::has_image(), Inter::skip_variable(), NotCond::skip_variable(), Add::skip_variable(), Monotonic::skip_variable(), Compose::skip_variable(), RightConcat::skip_variable(), and Fixpoint::skip_variable().
get_range()
virtual const GHom::range_t _GHom::get_range () const inline virtual inherited
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
Reimplemented in NotCond, Add, Monotonic, Compose, And, Fixpoint, _VarCompState, _setVarConst, _incVar, and _VarCompVar.
References GHom::full_range.
Referenced by GHom::get_range().
has_image()
GDDD StrongHom::has_image (const GDDD & d) const virtual
Reimplemented from _GHom.
References GDDD::begin(), GDDD::end(), GDDD::null, GDDD::one, phi(), phiOne(), GDDD::top, and GDDD::variable().
has_image_skip()
GDDD _GHom::has_image_skip (const GDDD & d) const inherited
References GDDD::begin(), GDDD::end(), _GHom::has_image(), GHom::has_image(), GHom::id, GDDD::null, GDDD::one, _GHom::skip_variable(), GDDD::top, and GDDD::variable().
hash()
virtual size_t _GHom::hash () const pure virtual inherited
Hash key computation.
It is essential for good hash table operation that the spread of the keys be as good as possible. Also, fast hash key computation is a good design goal. Note that bad hash functions will yield more collisions, thus equality comparisons which may be quite costly.
Implemented in Identity, Constant, Apply2k, DomExtract, Mult, Inter, NotCond, Add, Monotonic, Compose, And, LeftConcat, RightConcat, Minus, Fixpoint, MLHomAdapter, _VarCompState, _setVarConst, _incVar, and _VarCompVar.
invert()
virtual GHom _GHom::invert (const GDDD &) const inline virtual inherited
returns the predescessor homomorphism, using pot to determine variable domains
Reimplemented in Identity, Constant, Apply2k, Mult, Inter, Add, Monotonic, Compose, And, Minus, Fixpoint, _setVarConst, and _incVar.
References _GHom::GHom, _GHom::is_selector(), GDDD::null, and _GHom::print().
Referenced by GHom::invert().
is_selector()
virtual bool _GHom::is_selector () const inline virtual inherited
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
Reimplemented in Identity, Constant, DomExtract, Mult, Inter, NotCond, Add, Monotonic, Compose, And, Minus, Fixpoint, _VarCompState, and _VarCompVar.
Referenced by _GHom::invert(), and GHom::is_selector().
mark()
virtual void _GHom::mark () const inline virtual inherited
For garbage collection. Used in first phase of garbage collection.
Reimplemented in Constant, Apply2k, Mult, Inter, NotCond, Add, Monotonic, Compose, And, LeftConcat, RightConcat, Minus, Fixpoint, and MLHomAdapter.
Referenced by GHom::mark().
negate()
GHom _GHom::negate () const virtual inherited
returns a negation of a selector homomorphism h, such that h.negate() (d) = d - h(d)
Reimplemented in Identity, Constant, Inter, NotCond, Add, And, and _VarCompState.
References _GHom::GHom.
Referenced by GHom::negate().
operator<()
bool _GHom::operator< (const _GHom & h) const inherited
Ordering between _GHom. It is the chronological ordering of creation.
References _GHom::creation_counter.
operator==() [1/2]
bool StrongHom::operator== (const _GHom & h) const virtual
Comparator for unicity table.
Users should not use this. The behavior is to check for type mismatch (and return false if that is the case) or call specialized comparators of derived subclasses otherwise.
Implements _GHom.
operator==() [2/2]
virtual bool StrongHom::operator== (const StrongHom & h) const pure virtual
Comparator is pure virtual. Define a behavior in user homomorphisms.
Implemented in _VarCompState, _setVarConst, _incVar, and _VarCompVar.
phi()
virtual GHom StrongHom::phi (int var, int val) const pure virtual
Evaluation over an arbitrary arc of a SDD.
Parameters
var the index of the variable labeling the node.
val the value labeling the arc.
Returns
a homomorphism to apply on the successor node
Implemented in _VarCompState, _setVarConst, _incVar, and _VarCompVar.
Referenced by eval(), and has_image().
phiOne()
virtual GDDD StrongHom::phiOne () const inline virtual
Evaluation over terminal GDDD::one.
Returns a constant DDD. A homomorphism that does not overload phiOne does not expect to meet the terminal during it's evaluation, therefore default behavior returns GDDD::top
Reimplemented in _VarCompState, _setVarConst, _incVar, and _VarCompVar.
References GDDD::top.
Referenced by eval(), and has_image().
print()
void StrongHom::print (std::ostream & os) const virtual
pretty print
Implements _GHom.
Reimplemented in _VarCompState, _setVarConst, _incVar, and _VarCompVar.
skip_variable()
virtual bool _GHom::skip_variable (int) const inline virtual inherited
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
This is defined as a StrongHom with : phi(var,val) { if (skip_variable(var)) return GShom(var, val, this); else { real behavior } }
Reimplemented in DomExtract, Inter, NotCond, Add, Monotonic, Compose, And, RightConcat, Fixpoint, _incVar, _VarCompState, _setVarConst, _VarCompVar, and Identity.
Referenced by _GHom::eval_skip(), _GHom::has_image_skip(), Inter::skip_variable(), NotCond::skip_variable(), Add::skip_variable(), Monotonic::skip_variable(), Compose::skip_variable(), RightConcat::skip_variable(), Fixpoint::skip_variable(), and GHom::skip_variable().
Member Data Documentation
creation_counter
size_t _GHom::creation_counter private inherited
Counter of objects created (see constructors).
This is used for the ordering between homomorphisms.
Referenced by _GHom::_GHom(), and _GHom::operator<().
immediat
bool _GHom::immediat mutable private inherited
For operation cache management.
If immediat==true, eval is called without attempting a cache hit. Currently only the constant homomorphism has this attribute set to true.
Referenced by GHom::operator()().
marking
bool _GHom::marking mutable private inherited
For garbage collection.
Used in the two phase garbage collection process. A Hom that is not marked after the first pass over the unicity table, will be sweeped in the second phase. Outside of garbage collection routine, marking should always bear the value false.
Referenced by GHom::garbage(), and GHom::mark().
refCounter
int _GHom::refCounter mutable private inherited
For garbage collection.
Counts the number of times a _GShom is referenced from the context of an Shom.
Referenced by Hom::Hom(), Hom::Hom(), Hom::Hom(), Hom::Hom(), Hom::operator=(), Hom::operator=(), GHom::refCounter(), and Hom::~Hom().
The documentation for this class was generated from the following files:
Hom.h
Hom.cpp
Please comment this page and report errors about it on the RefDocComments page.