DDD: ext_hash_map< Key, Data, HashKey, EqualKey >::accessor Class Reference
ext_hash_map< Key, Data, HashKey, EqualKey >::accessor Class Reference
#include <util/ext_hash_map.hh>
Public Types
typedef std::pair< const Key, Data > value_type
Public Member Functions
value_type & operator* () const
value_type * operator-> () const
accessor ()
bool empty () const
void release ()
Private Member Functions
accessor (const accessor &)
accessor & operator= (const accessor &)
Private Attributes
bool has_result_
iterator current_bucket_
Friends
class ext_hash_map
Member Typedef Documentation
value_type
template<typename Key , typename Data , typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> typedef std::pair<const Key, Data> ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::value_type
Constructor & Destructor Documentation
accessor() [1/2]
template<typename Key , typename Data , typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::accessor () inline
accessor() [2/2]
template<typename Key , typename Data , typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::accessor (const accessor &) private
Member Function Documentation
empty()
template<typename Key , typename Data , typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> bool ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::empty () const inline
References ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::has_result_.
Referenced by MyNbStates::nbStates(), and MySDDNbStates::nbStates().
operator*()
template<typename Key , typename Data , typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> value_type & ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::operator* () const inline
References ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::current_bucket_.
Referenced by ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::operator->().
operator->()
template<typename Key , typename Data , typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> value_type * ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::operator-> () const inline
References ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::operator*().
operator=()
template<typename Key , typename Data , typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> accessor & ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::operator= (const accessor &) private
release()
template<typename Key , typename Data , typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> void ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::release () inline
Friends And Related Symbol Documentation
ext_hash_map
template<typename Key , typename Data , typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> friend class ext_hash_map friend
Member Data Documentation
current_bucket_
template<typename Key , typename Data , typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> iterator ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::current_bucket_ private
Referenced by ext_hash_map< Key, Data, HashKey, EqualKey >::find(), ext_hash_map< Key, Data, HashKey, EqualKey >::insert(), and ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::operator*().
has_result_
template<typename Key , typename Data , typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> bool ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::has_result_ private
Referenced by ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::empty(), ext_hash_map< Key, Data, HashKey, EqualKey >::find(), and ext_hash_map< Key, Data, HashKey, EqualKey >::insert().
The documentation for this class was generated from the following file:
util/ext_hash_map.hh
Please comment this page and report errors about it on the RefDocComments page.