DDD: _DED_Hom Class Reference
_DED_Hom Class Reference
Public Member Functions
size_t hash () const
bool operator== (const _DED &e) const
_DED * clone () const
GDDD eval () const
~_DED_Hom ()
Static Public Member Functions
static GDDD create (const GHom &h, const GDDD &d)
Public Attributes
GDDD result
Private Member Functions
_DED_Hom (const GHom &h, const GDDD &d)
Private Attributes
GHom hom
GDDD parameter
Constructor & Destructor Documentation
_DED_Hom()
_DED_Hom::_DED_Hom (const GHom & h, const GDDD & d) inline private
~_DED_Hom()
_DED_Hom::~_DED_Hom () inline
Member Function Documentation
clone()
_DED * _DED_Hom::clone () const inline virtual
Implements _DED.
create()
GDDD _DED_Hom::create (const GHom & h, const GDDD & d) static
References compute(), and GDDD::null.
eval()
GDDD _DED_Hom::eval () const virtual
Implements _DED.
References GHom::eval(), hom, and parameter.
hash()
size_t _DED_Hom::hash () const virtual
Implements _DED.
References GDDD::hash(), GHom::hash(), hom, and parameter.
operator==()
bool _DED_Hom::operator== (const _DED & e) const virtual
Implements _DED.
References hom, and parameter.
Member Data Documentation
hom
GHom _DED_Hom::hom private
Referenced by eval(), hash(), and operator==().
parameter
GDDD _DED_Hom::parameter private
Referenced by eval(), hash(), and operator==().
result
GDDD _DED::result inherited
The documentation for this class was generated from the following file:
DED.cpp
Please comment this page and report errors about it on the RefDocComments page.