DDD: nsMLShom::Identity Class Reference
nsMLShom::Identity Class Reference
Public Member Functions
Identity (int ref=0)
virtual bool shouldCache () const
test if caching should be done : default means should cache
bool operator== (const _MLShom &) const
size_t hash () const
unique table trivia
_MLShom * clone () const
bool skip_variable (int) const
SHomNodeMap eval (const GSDD &d) const
Private Member Functions
virtual void mark () const
For garbage collection. Used in first phase of garbage collection.
Private Attributes
int refCounter
For garbage collection.
bool marking
For garbage collection.
Constructor & Destructor Documentation
Identity()
nsMLShom::Identity::Identity (int ref = 0) inline
Referenced by clone().
Member Function Documentation
clone()
_MLShom* nsMLShom::Identity::clone () const inline virtual
Implements _MLShom.
References Identity().
eval()
SHomNodeMap nsMLShom::Identity::eval (const GSDD & d) const inline virtual
Implements _MLShom.
References AdditiveMap< K, V, EqualKey >::add(), and GShom::id.
hash()
size_t nsMLShom::Identity::hash () const inline virtual
unique table trivia
Implements _MLShom.
mark()
virtual void _MLShom::mark () const inline private virtual inherited
For garbage collection. Used in first phase of garbage collection.
operator==()
bool nsMLShom::Identity::operator== (const _MLShom &) const inline virtual
Implements _MLShom.
shouldCache()
virtual bool nsMLShom::Identity::shouldCache () const inline virtual
test if caching should be done : default means should cache
Reimplemented from _MLShom.
skip_variable()
bool nsMLShom::Identity::skip_variable (int) const inline
Member Data Documentation
marking
bool _MLShom::marking mutable private inherited
For garbage collection.
Used in the two phase garbage collection process. A Shom that is not marked after the first pass over the unicity table, will be sweeped in the second phase. Outside of garbage collection routine, marking should always bear the value false.
Referenced by MLShom::garbage().
refCounter
int _MLShom::refCounter mutable private inherited
For garbage collection.
Counts the number of times a _MLHom is referenced from the context of an MLHom.
The documentation for this class was generated from the following file:
MLSHom.cpp
Please comment this page and report errors about it on the RefDocComments page.