DDD: dotHighlight Class Reference
dotHighlight Class Reference
a more evolved API for highlighting parts of a graph
#include <util/dotExporter.h>
Public Member Functions
virtual ~dotHighlight ()
dotHighlight (const string &path)
void initialize (const string &path)
void setVarAlignment (bool isAligned)
void addSDD (const GSDD &g)
void addSDD (const GSDD &g, const string &label)
void setColor (const GSDD &g, const string &color)
void exportDot ()
Private Attributes
class dotExporter * de
Detailed Description
a more evolved API for highlighting parts of a graph
Constructor & Destructor Documentation
~dotHighlight()
dotHighlight::~dotHighlight () virtual
References de.
dotHighlight()
dotHighlight::dotHighlight (const string & path)
References de, and setVarAlignment().
Member Function Documentation
addSDD() [1/2]
void dotHighlight::addSDD (const GSDD & g)
References dotExporter::collect(), and de.
Referenced by addSDD().
addSDD() [2/2]
void dotHighlight::addSDD (const GSDD & g, const string & label)
References dotExporter::collect(), de, and dotExporter::label().
exportDot()
void dotHighlight::exportDot ()
References de, and dotExporter::finish().
Referenced by exportUniqueTable().
initialize()
void dotHighlight::initialize (const string & path)
References de, dotExporter::init(), and dotExporter::setPath().
Referenced by exportUniqueTable().
setColor()
void dotHighlight::setColor (const GSDD & g, const string & color)
References de, and dotExporter::setColor().
Referenced by exportUniqueTable().
setVarAlignment()
void dotHighlight::setVarAlignment (bool isAligned)
References de, and dotExporter::setAlign().
Referenced by dotHighlight().
Member Data Documentation
de
class dotExporter* dotHighlight::de private
Referenced by addSDD(), addSDD(), dotHighlight(), exportDot(), initialize(), setColor(), setVarAlignment(), and ~dotHighlight().
The documentation for this class was generated from the following files:
util/dotExporter.h
util/dotExporter.cpp
Please comment this page and report errors about it on the RefDocComments page.