DDD: nsMLHom::GHomAdapter Class Reference
nsMLHom::GHomAdapter Class Reference
Public Member Functions
GHomAdapter (const GHom &_h, int ref=0)
bool operator== (const _MLHom &other) const
size_t hash () const
unique table trivia
_MLHom * clone () const
bool skip_variable (int var) const
HomNodeMap eval (const GDDD &d) const
virtual bool shouldCache () const
test if caching should be done : default means should cache
Private Member Functions
virtual void mark () const
For garbage collection. Used in first phase of garbage collection.
Private Attributes
GHom h
int refCounter
For garbage collection.
bool marking
For garbage collection.
Constructor & Destructor Documentation
GHomAdapter()
nsMLHom::GHomAdapter::GHomAdapter (const GHom & _h, int ref = 0) inline
Referenced by clone().
Member Function Documentation
clone()
_MLHom* nsMLHom::GHomAdapter::clone () const inline virtual
Implements _MLHom.
References GHomAdapter().
eval()
HomNodeMap nsMLHom::GHomAdapter::eval (const GDDD & d) const inline virtual
Implements _MLHom.
References AdditiveMap< K, V, EqualKey >::add(), h, and GHom::id.
hash()
size_t nsMLHom::GHomAdapter::hash () const inline virtual
unique table trivia
Implements _MLHom.
References h, and GHom::hash().
mark()
virtual void _MLHom::mark () const inline private virtual inherited
For garbage collection. Used in first phase of garbage collection.
operator==()
bool nsMLHom::GHomAdapter::operator== (const _MLHom & other) const inline virtual
Implements _MLHom.
References h.
shouldCache()
virtual bool _MLHom::shouldCache () const inline virtual inherited
test if caching should be done : default means should cache
Reimplemented in nsMLHom::Identity.
skip_variable()
bool nsMLHom::GHomAdapter::skip_variable (int var) const inline
References h, and GHom::skip_variable().
Member Data Documentation
h
GHom nsMLHom::GHomAdapter::h private
Referenced by eval(), hash(), operator==(), and skip_variable().
marking
bool _MLHom::marking mutable private inherited
For garbage collection.
Used in the two phase garbage collection process. A Shom that is not marked after the first pass over the unicity table, will be sweeped in the second phase. Outside of garbage collection routine, marking should always bear the value false.
Referenced by MLHom::garbage().
refCounter
int _MLHom::refCounter mutable private inherited
For garbage collection.
Counts the number of times a _MLHom is referenced from the context of an MLHom.
The documentation for this class was generated from the following file:
MLHom.cpp
Please comment this page and report errors about it on the RefDocComments page.