DDD: MyGShom Class Reference
MyGShom Class Reference abstract
#include <SHom.h>
Public Member Functions
GSDD has_image_skip (const GSDD &) const
virtual bool skip_variable (int) const
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
virtual bool is_selector () const
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
virtual const GShom::range_t get_range () const
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
virtual bool operator== (const _GShom &h) const =0
Comparator.
virtual size_t hash () const =0
Hash key computation.
virtual _GShom * clone () const =0
virtual GSDD has_image (const GSDD &d) const
virtual GShom compose (const GShom &) const
virtual GSDD eval (const GSDD &) const =0
The computation function responsible for evaluation over a node.
virtual void mark () const
For garbage collection. Used in first phase of garbage collection.
void mark_if_refd () const
void ref () const
void deref () const
unsigned long int refCounter () const
bool is_marked () const
void set_mark (bool val) const
virtual void print (std::ostream &os) const =0
virtual GShom invert (const GSDD &) const
Static Public Member Functions
static const _GShom * get_concret (const GShom &gshom)
TODO : this is a dirty trick to allow us to do terms rewriting in Add, Fixpoint etc... A more elegant architecture would be nice.
Private Member Functions
GSDD eval_skip (const GSDD &) const
The procedure responsible for propagating efficiently across "skipped" variable nodes.
virtual bool immediat () const
For operation cache management.
Private Attributes
int _refCounter
For garbage collection.
Member Function Documentation
clone()
virtual _GShom * _GShom::clone () const pure virtual inherited
Implemented in sns::Identity, sns::Constant, sns::SApply2k, sns::Mult, sns::Inter, sns::SDomExtract, sns::LocalApply, sns::SLocalApply, sns::SNotCond, sns::And, sns::Add, sns::RecFireSat, sns::Compose, sns::LeftConcat, sns::RightConcat, sns::Minus, sns::HomMinus, sns::Fixpoint, and sns::MLShomAdapter.
compose()
GShom _GShom::compose (const GShom & r) const virtual inherited
References GShom::id, and GSDD::null.
Referenced by GShom::compose().
deref()
void _GShom::deref () const inline inherited
References _GShom::_refCounter.
Referenced by Shom::operator=(), Shom::operator=(), and Shom::~Shom().
eval()
virtual GSDD _GShom::eval (const GSDD &) const pure virtual inherited
The computation function responsible for evaluation over a node.
Users should not directly use this. Normal behavior is to use GShom::operator() that encapsulates this call with operation caching.
Implemented in StrongShom, sns::Identity, sns::Constant, sns::SApply2k, sns::Mult, sns::Inter, sns::SDomExtract, sns::LocalApply, sns::SLocalApply, sns::SNotCond, sns::And, sns::Add, sns::RecFireSat, sns::Compose, sns::LeftConcat, sns::RightConcat, sns::Minus, sns::HomMinus, sns::Fixpoint, and sns::MLShomAdapter.
Referenced by _GShom::eval_skip().
eval_skip()
GSDD _GShom::eval_skip (const GSDD & d) const private inherited
The procedure responsible for propagating efficiently across "skipped" variable nodes.
References GSDD::begin(), GSDD::end(), _GShom::eval(), GShom::id, _GShom::immediat(), GSDD::nbsons(), GSDD::null, GSDD::one, _GShom::skip_variable(), square_union(), GSDD::top, and GSDD::variable().
Referenced by GShom::eval().
get_concret()
static const _GShom * _GShom::get_concret (const GShom & gshom) inline static inherited
TODO : this is a dirty trick to allow us to do terms rewriting in Add, Fixpoint etc... A more elegant architecture would be nice.
References GShom::concret.
Referenced by addCompositionParameter(), addParameter(), buildUnionParameters(), sns::RecFireSat::eval(), sns::Fixpoint::eval(), sns::Add::factorizeByLevel(), GShom::GShom(), sns::Fixpoint::has_image(), operator!(), operator*(), sns::recFireSat(), sns::Inter::skip_variable(), sns::Add::skip_variable(), and sns::RightConcat::skip_variable().
get_range()
virtual const GShom::range_t _GShom::get_range () const inline virtual inherited
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
Reimplemented in sns::LocalApply, sns::SLocalApply, sns::SNotCond, sns::And, sns::Add, sns::RecFireSat, sns::Compose, and sns::Fixpoint.
References GShom::full_range.
Referenced by GShom::get_range().
has_image()
GSDD _GShom::has_image (const GSDD & d) const virtual inherited
Reimplemented in sns::Identity, sns::Inter, sns::LocalApply, sns::SLocalApply, sns::SNotCond, sns::And, sns::Add, sns::Compose, sns::LeftConcat, sns::RightConcat, sns::Fixpoint, and StrongShom.
References _GShom::GShom.
Referenced by sns::Inter::has_image(), sns::SNotCond::has_image(), sns::Compose::has_image(), sns::Fixpoint::has_image(), and _GShom::has_image_skip().
has_image_skip()
GSDD _GShom::has_image_skip (const GSDD & d) const inherited
References GSDD::begin(), GSDD::end(), GShom::has_image(), _GShom::has_image(), GShom::id, GSDD::null, GSDD::one, _GShom::skip_variable(), GSDD::top, and GSDD::variable().
hash()
virtual size_t _GShom::hash () const pure virtual inherited
Hash key computation.
It is essential for good hash table operation that the spread of the keys be as good as possible. Also, fast hash key computation is a good design goal. Note that bad hash functions will yield more collisions, thus equality comparisons which may be quite costly.
Implemented in sns::Identity, sns::Constant, sns::SApply2k, sns::Mult, sns::Inter, sns::SDomExtract, sns::LocalApply, sns::SLocalApply, sns::SNotCond, sns::And, sns::Add, sns::RecFireSat, sns::Compose, sns::LeftConcat, sns::RightConcat, sns::Minus, sns::HomMinus, sns::Fixpoint, and sns::MLShomAdapter.
immediat()
virtual bool _GShom::immediat () const inline private virtual inherited
For operation cache management.
If immediat==true, eval is called without attempting a cache hit. Currently only the constant homomorphism has this attribute set to true. Overload and return true for immediate computations.
Reimplemented in sns::Identity, and sns::Constant.
Referenced by _GShom::eval_skip(), and GShom::operator()().
invert()
virtual GShom _GShom::invert (const GSDD &) const inline virtual inherited
Reimplemented in sns::Identity, sns::Constant, sns::SApply2k, sns::Mult, sns::Inter, sns::LocalApply, sns::SLocalApply, sns::And, sns::Add, sns::RecFireSat, sns::Compose, sns::Minus, sns::HomMinus, and sns::Fixpoint.
References _GShom::is_selector(), Shom::null, and _GShom::print().
Referenced by GShom::invert().
is_marked()
bool _GShom::is_marked () const inline inherited
References _GShom::_refCounter.
Referenced by _GShom::set_mark().
is_selector()
virtual bool _GShom::is_selector () const inline virtual inherited
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
Reimplemented in sns::Identity, sns::Constant, sns::SApply2k, sns::Mult, sns::Inter, sns::SDomExtract, sns::LocalApply, sns::SLocalApply, sns::SNotCond, sns::And, sns::Add, sns::RecFireSat, sns::Compose, sns::Minus, sns::HomMinus, and sns::Fixpoint.
Referenced by _GShom::invert(), and GShom::is_selector().
mark()
virtual void _GShom::mark () const inline virtual inherited
For garbage collection. Used in first phase of garbage collection.
Reimplemented in sns::Constant, sns::SApply2k, sns::Mult, sns::Inter, sns::LocalApply, sns::SLocalApply, sns::SNotCond, sns::And, sns::Add, sns::RecFireSat, sns::Compose, sns::LeftConcat, sns::RightConcat, sns::Minus, sns::HomMinus, sns::Fixpoint, and sns::MLShomAdapter.
Referenced by _GShom::set_mark().
mark_if_refd()
void _GShom::mark_if_refd () const inline inherited
References _GShom::refCounter(), and _GShom::set_mark().
operator==()
virtual bool _GShom::operator== (const _GShom & h) const pure virtual inherited
Comparator.
Used in case of hash collision. Should be appropriately defined in derived classes, in particular in user defined homomorphisms.
Implemented in sns::Identity, sns::Constant, sns::SApply2k, sns::Mult, sns::Inter, sns::And, sns::Add, sns::RecFireSat, sns::Compose, sns::LeftConcat, sns::RightConcat, sns::Minus, sns::HomMinus, sns::Fixpoint, StrongShom, sns::MLShomAdapter, sns::SDomExtract, sns::LocalApply, sns::SLocalApply, and sns::SNotCond.
print()
virtual void _GShom::print (std::ostream & os) const pure virtual inherited
Implemented in sns::Identity, sns::Constant, sns::SApply2k, sns::Mult, sns::Inter, sns::SDomExtract, sns::LocalApply, sns::SLocalApply, sns::SNotCond, sns::And, sns::Add, sns::RecFireSat, sns::Compose, sns::LeftConcat, sns::RightConcat, sns::Minus, sns::HomMinus, sns::Fixpoint, sns::MLShomAdapter, and StrongShom.
Referenced by _GShom::invert().
ref()
void _GShom::ref () const inline inherited
References _GShom::_refCounter.
Referenced by Shom::operator=(), Shom::operator=(), Shom::Shom(), Shom::Shom(), Shom::Shom(), and Shom::Shom().
refCounter()
unsigned long int _GShom::refCounter () const inline inherited
References _GShom::_refCounter.
Referenced by _GShom::mark_if_refd(), Shom::operator=(), Shom::operator=(), GShom::refCounter(), and Shom::~Shom().
set_mark()
void _GShom::set_mark (bool val) const inline inherited
References _GShom::_refCounter, _GShom::is_marked(), and _GShom::mark().
Referenced by GShom::garbage(), GShom::mark(), and _GShom::mark_if_refd().
skip_variable()
virtual bool _GShom::skip_variable (int) const inline virtual inherited
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
This is defined as a StrongHom with : phi(var,val) { if (skip_variable(var)) return GShom(var, val, this); else { real behavior } }
Reimplemented in sns::SApply2k, sns::Inter, sns::LocalApply, sns::SLocalApply, sns::SNotCond, sns::And, sns::Add, sns::RecFireSat, sns::Compose, sns::RightConcat, sns::Fixpoint, sns::Identity, and sns::SDomExtract.
Referenced by _GShom::eval_skip(), _GShom::has_image_skip(), sns::Inter::skip_variable(), sns::Add::skip_variable(), sns::RightConcat::skip_variable(), and GShom::skip_variable().
Member Data Documentation
_refCounter
int _GShom::_refCounter mutable private inherited
For garbage collection.
Counts the number of times a _GShom is referenced from the context of an Shom. For garbage collection: lowest bit of refCounter gives marking value for mark&sweep. Used in the two phase garbage collection process. A Shom that is not marked after the first pass over the unicity table, will be sweeped in the second phase. Outside of garbage collection routine, marking should always bear the value false.
Referenced by _GShom::deref(), _GShom::is_marked(), _GShom::ref(), _GShom::refCounter(), and _GShom::set_mark().
The documentation for this class was generated from the following file:
SHom.h
Please comment this page and report errors about it on the RefDocComments page.