DDD: _SDED_Mult Class Reference
_SDED_Mult Class Reference
Public Member Functions
size_t hash () const
bool operator== (const _SDED &e) const
_SDED * clone () const
GSDD eval () const
~_SDED_Mult ()
Static Public Member Functions
static GSDD create (const GSDD &g1, const GSDD &g2)
Public Attributes
GSDD result
Private Member Functions
_SDED_Mult (const GSDD &g1, const GSDD &g2)
Private Attributes
GSDD parameter1
GSDD parameter2
Constructor & Destructor Documentation
_SDED_Mult()
_SDED_Mult::_SDED_Mult (const GSDD & g1, const GSDD & g2) inline private
Referenced by clone(), and create().
~_SDED_Mult()
_SDED_Mult::~_SDED_Mult () inline
Member Function Documentation
clone()
_SDED* _SDED_Mult::clone () const inline virtual
Implements _SDED.
References _SDED_Mult().
create()
GSDD _SDED_Mult::create (const GSDD & g1, const GSDD & g2) static
References _SDED_Mult(), compute(), GSDD::hash(), GSDD::null, GSDD::one, GSDD::top, and GSDD::variable().
Referenced by operator*().
eval()
GSDD _SDED_Mult::eval () const virtual
Implements _SDED.
References GSDD::begin(), DataSet::empty(), GSDD::end(), GSDD::null, parameter1, parameter2, DataSet::set_intersect(), square_union(), and GSDD::variable().
hash()
size_t _SDED_Mult::hash () const virtual
Implements _SDED.
References GSDD::hash(), parameter1, and parameter2.
operator==()
bool _SDED_Mult::operator== (const _SDED & e) const virtual
Implements _SDED.
References parameter1, and parameter2.
Member Data Documentation
parameter1
GSDD _SDED_Mult::parameter1 private
Referenced by eval(), hash(), and operator==().
parameter2
GSDD _SDED_Mult::parameter2 private
Referenced by eval(), hash(), and operator==().
result
GSDD _SDED::result inherited
The documentation for this class was generated from the following file:
SDED.cpp
Please comment this page and report errors about it on the RefDocComments page.