DDD: _DED_Minus Class Reference
_DED_Minus Class Reference
Public Member Functions
size_t hash () const
bool operator== (const _DED &e) const
_DED * clone () const
GDDD eval () const
~_DED_Minus ()
Static Public Member Functions
static GDDD create (const GDDD &g1, const GDDD &g2)
Public Attributes
GDDD result
Private Member Functions
_DED_Minus (const GDDD &g1, const GDDD &g2)
Private Attributes
GDDD parameter1
GDDD parameter2
Constructor & Destructor Documentation
_DED_Minus()
_DED_Minus::_DED_Minus (const GDDD & g1, const GDDD & g2) inline private
Referenced by clone(), and create().
~_DED_Minus()
_DED_Minus::~_DED_Minus () inline
Member Function Documentation
clone()
_DED* _DED_Minus::clone () const inline virtual
Implements _DED.
References _DED_Minus().
create()
GDDD _DED_Minus::create (const GDDD & g1, const GDDD & g2) static
References _DED_Minus(), compute(), GDDD::null, GDDD::one, GDDD::top, and GDDD::variable().
Referenced by operator-().
eval()
GDDD _DED_Minus::eval () const virtual
Implements _DED.
References GDDD::begin(), GDDD::end(), GDDD::nbsons(), GDDD::null, parameter1, parameter2, and GDDD::variable().
hash()
size_t _DED_Minus::hash () const virtual
Implements _DED.
References GDDD::hash(), parameter1, and parameter2.
operator==()
bool _DED_Minus::operator== (const _DED & e) const virtual
Implements _DED.
References parameter1, and parameter2.
Member Data Documentation
parameter1
GDDD _DED_Minus::parameter1 private
Referenced by eval(), hash(), and operator==().
parameter2
GDDD _DED_Minus::parameter2 private
Referenced by eval(), hash(), and operator==().
result
GDDD _DED::result inherited
The documentation for this class was generated from the following file:
DED.cpp
Please comment this page and report errors about it on the RefDocComments page.