DDD: MySize Class Reference
MySize Class Reference
Public Member Functions
unsigned long int operator() (const GDDD &g)
Private Member Functions
void mysize (const GDDD &g)
Private Attributes
unsigned long int res
std::set< GDDD > s
Member Function Documentation
mysize()
void MySize::mysize (const GDDD & g) inline private
References GDDD::begin(), GDDD::end(), mysize(), res, and s.
Referenced by mysize(), and operator()().
operator()()
unsigned long int MySize::operator() (const GDDD & g) inline
References mysize(), res, and s.
Member Data Documentation
res
unsigned long int MySize::res private
Referenced by mysize(), and operator()().
s
std::set<GDDD> MySize::s private
Referenced by mysize(), and operator()().
The documentation for this class was generated from the following file:
DDD.cpp
Please comment this page and report errors about it on the RefDocComments page.