DDD: nsMLHom::Add Class Reference
nsMLHom::Add Class Reference
Public Member Functions
Add (const std::set< MLHom > &s, int ref=0)
bool operator== (const _MLHom &h) const
_MLHom * clone () const
size_t hash () const
unique table trivia
bool skip_variable (int) const
HomNodeMap eval (const GDDD &d) const
virtual bool shouldCache () const
test if caching should be done : default means should cache
Private Member Functions
virtual void mark () const
For garbage collection. Used in first phase of garbage collection.
Private Attributes
std::set< MLHom > parameters
int refCounter
For garbage collection.
bool marking
For garbage collection.
Constructor & Destructor Documentation
Add()
nsMLHom::Add::Add (const std::set< MLHom > & s, int ref = 0) inline
Referenced by clone().
Member Function Documentation
clone()
_MLHom* nsMLHom::Add::clone () const inline virtual
Implements _MLHom.
References Add().
eval()
HomNodeMap nsMLHom::Add::eval (const GDDD & d) const inline virtual
Implements _MLHom.
References AdditiveMap< K, V, EqualKey >::addAll(), and parameters.
hash()
size_t nsMLHom::Add::hash () const inline virtual
unique table trivia
Implements _MLHom.
References parameters.
mark()
virtual void _MLHom::mark () const inline private virtual inherited
For garbage collection. Used in first phase of garbage collection.
operator==()
bool nsMLHom::Add::operator== (const _MLHom & h) const inline virtual
Implements _MLHom.
References parameters.
shouldCache()
virtual bool _MLHom::shouldCache () const inline virtual inherited
test if caching should be done : default means should cache
Reimplemented in nsMLHom::Identity.
skip_variable()
bool nsMLHom::Add::skip_variable (int) const inline
Member Data Documentation
marking
bool _MLHom::marking mutable private inherited
For garbage collection.
Used in the two phase garbage collection process. A Shom that is not marked after the first pass over the unicity table, will be sweeped in the second phase. Outside of garbage collection routine, marking should always bear the value false.
Referenced by MLHom::garbage().
parameters
std::set<MLHom> nsMLHom::Add::parameters private
Referenced by eval(), hash(), and operator==().
refCounter
int _MLHom::refCounter mutable private inherited
For garbage collection.
Counts the number of times a _MLHom is referenced from the context of an MLHom.
The documentation for this class was generated from the following file:
MLHom.cpp
Please comment this page and report errors about it on the RefDocComments page.