DDD: dotExporter Class Reference
dotExporter Class Reference
Public Types
typedef d3::hash_set< GSDD >::type gsdd_hash_set
Public Member Functions
virtual ~dotExporter ()
void setPath (const string &path)
virtual void collect (const GSDD &g)
void collect (const GDDD &g)
dotExporter (const string &s="test", bool multiT=false)
void printColor (const GSDD &g, const string &color, gsdd_hash_set &visited)
void setColor (const GSDD &g, const string &color)
void init ()
void setAlign (bool align)
void label (const GSDD &g, const string &name)
int operator() (const GSDD &g)
void printLevels ()
void finish ()
Protected Types
typedef std::set< int > seen_t
typedef seen_t::const_iterator seen_it
typedef seen_t::const_reverse_iterator seen_rit
Protected Member Functions
void collect (const SDD &g)
void collect (const DDD &g)
Protected Attributes
map< GSDD, string > name
map< GDDD, string > d3name
map< GDDD, string > entryd3Name
map< GDDD, int > entryd3Nb
map< GSDD, string > entryName
map< GSDD, int > entryNb
int nextid
int nextPid
int nextMid
int nextAid
string path
ostream * D3out
ostream * out
bool multiT
bool isAligned
seen_t seen
Member Typedef Documentation
gsdd_hash_set
typedef d3::hash_set<GSDD>::type dotExporter::gsdd_hash_set
seen_it
typedef seen_t::const_iterator dotExporter::seen_it protected
seen_rit
typedef seen_t::const_reverse_iterator dotExporter::seen_rit protected
seen_t
typedef std::set<int> dotExporter::seen_t protected
Constructor & Destructor Documentation
~dotExporter()
virtual dotExporter::~dotExporter () inline virtual
dotExporter()
dotExporter::dotExporter (const string & s = "test", bool multiT = false) inline
Member Function Documentation
collect() [1/4]
void dotExporter::collect (const DDD & g) inline protected
References collect().
collect() [2/4]
void dotExporter::collect (const GDDD & g) inline
References GDDD::begin(), collect(), d3name, D3out, GDDD::end(), GDDD::getvarName(), nextid, GDDD::null, GDDD::one, GDDD::top, and GDDD::variable().
collect() [3/4]
virtual void dotExporter::collect (const GSDD & g) inline virtual
increment in loop
Reimplemented in hDotExporter.
References GDDD::begin(), GSDD::begin(), collect(), GDDD::end(), GSDD::end(), entryd3Name, entryd3Nb, entryName, entryNb, multiT, name, nextAid, nextid, nextPid, GDDD::one, GSDD::one, out, GSDD::refCounter(), seen, GSDD::top, and GSDD::variable().
collect() [4/4]
void dotExporter::collect (const SDD & g) inline protected
References collect().
Referenced by dotHighlight::addSDD(), dotHighlight::addSDD(), collect(), collect(), collect(), hDotExporter::collect(), collect(), label(), operator()(), and setColor().
finish()
void dotExporter::finish () inline
References d3name, D3out, entryd3Name, entryd3Nb, entryName, entryNb, isAligned, name, out, and printLevels().
Referenced by dotHighlight::exportDot(), and operator()().
init()
void dotExporter::init () inline
References d3name, D3out, entryd3Name, entryd3Nb, entryName, entryNb, name, nextAid, nextid, nextMid, nextPid, out, path, and seen.
Referenced by exportDot(), dotHighlight::initialize(), and operator()().
label()
void dotExporter::label (const GSDD & g, const string & name) inline
References collect(), entryName, and name.
Referenced by dotHighlight::addSDD().
operator()()
int dotExporter::operator() (const GSDD & g) inline
References collect(), finish(), and init().
printColor()
void dotExporter::printColor (const GSDD & g, const string & color, gsdd_hash_set & visited) inline
References GSDD::begin(), GSDD::end(), name, out, and printColor().
Referenced by printColor(), and setColor().
printLevels()
void dotExporter::printLevels () inline
References name, GSDD::null, GSDD::one, out, seen, and GSDD::top.
Referenced by finish().
setAlign()
void dotExporter::setAlign (bool align) inline
References isAligned.
Referenced by dotHighlight::setVarAlignment().
setColor()
void dotExporter::setColor (const GSDD & g, const string & color) inline
References collect(), and printColor().
Referenced by dotHighlight::setColor().
setPath()
void dotExporter::setPath (const string & path) inline
References path.
Referenced by dotHighlight::initialize().
Member Data Documentation
d3name
map<GDDD,string> dotExporter::d3name protected
Referenced by collect(), finish(), and init().
D3out
ostream* dotExporter::D3out protected
Referenced by collect(), finish(), and init().
entryd3Name
map<GDDD,string> dotExporter::entryd3Name protected
Referenced by collect(), hDotExporter::collect(), finish(), and init().
entryd3Nb
map<GDDD,int> dotExporter::entryd3Nb protected
Referenced by collect(), hDotExporter::collect(), finish(), and init().
entryName
map<GSDD,string> dotExporter::entryName protected
Referenced by collect(), finish(), init(), and label().
entryNb
map<GSDD,int> dotExporter::entryNb protected
Referenced by collect(), finish(), and init().
isAligned
bool dotExporter::isAligned protected
Referenced by finish(), and setAlign().
multiT
bool dotExporter::multiT protected
Referenced by collect().
name
map<GSDD,string> dotExporter::name protected
Referenced by collect(), hDotExporter::collect(), finish(), init(), label(), printColor(), and printLevels().
nextAid
int dotExporter::nextAid protected
Referenced by collect(), hDotExporter::collect(), and init().
nextid
int dotExporter::nextid protected
Referenced by collect(), collect(), hDotExporter::collect(), and init().
nextMid
int dotExporter::nextMid protected
Referenced by init().
nextPid
int dotExporter::nextPid protected
Referenced by collect(), hDotExporter::collect(), and init().
out
ostream* dotExporter::out protected
Referenced by collect(), hDotExporter::collect(), finish(), init(), printColor(), and printLevels().
path
string dotExporter::path protected
Referenced by init(), and setPath().
seen
seen_t dotExporter::seen protected
Referenced by collect(), init(), and printLevels().
The documentation for this class was generated from the following file:
util/dotExporter.cpp
Please comment this page and report errors about it on the RefDocComments page.