DDD: _SDED_Add Class Reference
_SDED_Add Class Reference
Public Member Functions
size_t hash () const
bool operator== (const _SDED &e) const
_SDED * clone () const
GSDD eval () const
~_SDED_Add ()
Static Public Member Functions
static GSDD create (const GSDD &g1, const GSDD &g2)
static GSDD create (const d3::set< GSDD >::type &d)
Public Attributes
GSDD result
Private Types
typedef std::vector< GSDD > parameters_t
typedef parameters_t::const_iterator parameters_it
Private Member Functions
_SDED_Add (const d3::set< GSDD >::type &d)
Private Attributes
parameters_t parameters
Member Typedef Documentation
parameters_it
typedef parameters_t::const_iterator _SDED_Add::parameters_it private
parameters_t
typedef std::vector<GSDD> _SDED_Add::parameters_t private
Constructor & Destructor Documentation
_SDED_Add()
_SDED_Add::_SDED_Add (const d3::set< GSDD >::type & d) inline private
Referenced by clone(), and create().
~_SDED_Add()
_SDED_Add::~_SDED_Add () inline
Member Function Documentation
clone()
_SDED* _SDED_Add::clone () const inline virtual
Implements _SDED.
References _SDED_Add().
create() [1/2]
GSDD _SDED_Add::create (const d3::set< GSDD >::type & d) static
References _SDED_Add(), compute(), GSDD::null, GSDD::one, parameters, and GSDD::top.
create() [2/2]
GSDD _SDED_Add::create (const GSDD & g1, const GSDD & g2) static
References _SDED_Add(), compute(), GSDD::null, GSDD::one, parameters, GSDD::top, and GSDD::variable().
Referenced by SDED::add(), and operator+().
eval()
GSDD _SDED_Add::eval () const virtual
Implements _SDED.
References DataSet::empty(), DataSet::empty_set(), DataSet::newcopy(), GSDD::null, parameters, DataSet::set_equal(), DataSet::set_intersect(), DataSet::set_minus(), and square_union().
hash()
size_t _SDED_Add::hash () const virtual
Implements _SDED.
References parameters.
operator==()
bool _SDED_Add::operator== (const _SDED & e) const virtual
Implements _SDED.
References parameters.
Member Data Documentation
parameters
parameters_t _SDED_Add::parameters private
Referenced by create(), eval(), hash(), and operator==().
result
GSDD _SDED::result inherited
The documentation for this class was generated from the following file:
SDED.cpp
Please comment this page and report errors about it on the RefDocComments page.