DDD: _SDED_Minus Class Reference
_SDED_Minus Class Reference
Public Member Functions
size_t hash () const
bool operator== (const _SDED &e) const
_SDED * clone () const
GSDD eval () const
~_SDED_Minus ()
Static Public Member Functions
static GSDD create (const GSDD &g1, const GSDD &g2)
Public Attributes
GSDD result
Private Member Functions
_SDED_Minus (const GSDD &g1, const GSDD &g2)
Private Attributes
GSDD parameter1
GSDD parameter2
Constructor & Destructor Documentation
_SDED_Minus()
_SDED_Minus::_SDED_Minus (const GSDD & g1, const GSDD & g2) inline private
Referenced by clone(), and create().
~_SDED_Minus()
_SDED_Minus::~_SDED_Minus () inline
Member Function Documentation
clone()
_SDED* _SDED_Minus::clone () const inline virtual
Implements _SDED.
References _SDED_Minus().
create()
GSDD _SDED_Minus::create (const GSDD & g1, const GSDD & g2) static
References _SDED_Minus(), compute(), GSDD::null, GSDD::one, GSDD::top, and GSDD::variable().
Referenced by operator-().
eval()
GSDD _SDED_Minus::eval () const virtual
Implements _SDED.
References GSDD::begin(), DataSet::empty(), GSDD::end(), GSDD::null, parameter1, parameter2, DataSet::set_intersect(), DataSet::set_minus(), square_union(), and GSDD::variable().
hash()
size_t _SDED_Minus::hash () const virtual
Implements _SDED.
References GSDD::hash(), parameter1, and parameter2.
operator==()
bool _SDED_Minus::operator== (const _SDED & e) const virtual
Implements _SDED.
References parameter1, and parameter2.
Member Data Documentation
parameter1
GSDD _SDED_Minus::parameter1 private
Referenced by eval(), hash(), and operator==().
parameter2
GSDD _SDED_Minus::parameter2 private
Referenced by eval(), hash(), and operator==().
result
GSDD _SDED::result inherited
The documentation for this class was generated from the following file:
SDED.cpp
Please comment this page and report errors about it on the RefDocComments page.