DDD: nsMLShom::Add Class Reference
nsMLShom::Add Class Reference
Public Member Functions
Add (const std::set< MLShom > &s, int ref=0)
bool operator== (const _MLShom &h) const
_MLShom * clone () const
size_t hash () const
unique table trivia
bool skip_variable (int) const
SHomNodeMap eval (const GSDD &d) const
virtual bool shouldCache () const
test if caching should be done : default means should cache
Private Member Functions
virtual void mark () const
For garbage collection. Used in first phase of garbage collection.
Private Attributes
std::set< MLShom > parameters
int refCounter
For garbage collection.
bool marking
For garbage collection.
Constructor & Destructor Documentation
Add()
nsMLShom::Add::Add (const std::set< MLShom > & s, int ref = 0) inline
Referenced by clone().
Member Function Documentation
clone()
_MLShom* nsMLShom::Add::clone () const inline virtual
Implements _MLShom.
References Add().
eval()
SHomNodeMap nsMLShom::Add::eval (const GSDD & d) const inline virtual
Implements _MLShom.
References AdditiveMap< K, V, EqualKey >::addAll(), and parameters.
hash()
size_t nsMLShom::Add::hash () const inline virtual
unique table trivia
Implements _MLShom.
References parameters.
mark()
virtual void _MLShom::mark () const inline private virtual inherited
For garbage collection. Used in first phase of garbage collection.
operator==()
bool nsMLShom::Add::operator== (const _MLShom & h) const inline virtual
Implements _MLShom.
References parameters.
shouldCache()
virtual bool _MLShom::shouldCache () const inline virtual inherited
test if caching should be done : default means should cache
Reimplemented in nsMLShom::Identity.
skip_variable()
bool nsMLShom::Add::skip_variable (int) const inline
Member Data Documentation
marking
bool _MLShom::marking mutable private inherited
For garbage collection.
Used in the two phase garbage collection process. A Shom that is not marked after the first pass over the unicity table, will be sweeped in the second phase. Outside of garbage collection routine, marking should always bear the value false.
Referenced by MLShom::garbage().
parameters
std::set<MLShom> nsMLShom::Add::parameters private
Referenced by eval(), hash(), and operator==().
refCounter
int _MLShom::refCounter mutable private inherited
For garbage collection.
Counts the number of times a _MLHom is referenced from the context of an MLHom.
The documentation for this class was generated from the following file:
MLSHom.cpp
Please comment this page and report errors about it on the RefDocComments page.