DDD: MySDDNbStates Class Reference
MySDDNbStates Class Reference
Public Member Functions
MySDDNbStates (int v)
long double operator() (const GSDD &g)
Static Public Member Functions
static void clear ()
Private Types
typedef ext_hash_map< GSDD, long double > cache_type
Private Member Functions
long double nbStates (const GSDD &g)
Private Attributes
int val
Static Private Attributes
static cache_type cache = ext_hash_map<GSDD,long double> ()
Member Typedef Documentation
cache_type
typedef ext_hash_map<GSDD,long double> MySDDNbStates::cache_type private
Constructor & Destructor Documentation
MySDDNbStates()
MySDDNbStates::MySDDNbStates (int v) inline
Member Function Documentation
clear()
static void MySDDNbStates::clear () inline static
References cache, and ext_hash_map< Key, Data, HashKey, EqualKey >::clear().
Referenced by GSDD::garbage().
nbStates()
long double MySDDNbStates::nbStates (const GSDD & g) inline private
References GSDD::begin(), cache, ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::empty(), GSDD::end(), ext_hash_map< Key, Data, HashKey, EqualKey >::find(), ext_hash_map< Key, Data, HashKey, EqualKey >::insert(), nbStates(), GSDD::null, GSDD::one, GSDD::top, and val.
Referenced by nbStates(), and operator()().
operator()()
long double MySDDNbStates::operator() (const GSDD & g) inline
References nbStates().
Member Data Documentation
cache
ext_hash_map< GSDD, long double > MySDDNbStates::cache = ext_hash_map<GSDD,long double> () static private
Referenced by clear(), and nbStates().
val
int MySDDNbStates::val private
Referenced by nbStates().
The documentation for this class was generated from the following file:
SDD.cpp
Please comment this page and report errors about it on the RefDocComments page.