DDD: _VarCompVar Class Reference
_VarCompVar Class Reference
Public Member Functions
_VarCompVar (int v1, comparator c, int v2)
bool skip_variable (int vr) const
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
const GHom::range_t get_range () const
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
GDDD phiOne () const
Evaluation over terminal GDDD::one.
GHom phi (int vr, int vl) const
Evaluation over an arbitrary arc of a SDD.
GHom compose (const GHom &other) const
size_t hash () const
Hash key computation.
bool is_selector () const
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
void print (std::ostream &os) const
pretty print
bool operator== (const StrongHom &s) const
Comparator is pure virtual. Define a behavior in user homomorphisms.
_GHom * clone () const
bool operator== (const _GHom &h) const
Comparator for unicity table.
GDDD eval (const GDDD &) const
The evaluation mechanism of strong homomorphisms.
virtual GDDD has_image (const GDDD &) const
GDDD has_image_skip (const GDDD &) const
virtual GHom invert (const GDDD &) const
returns the predescessor homomorphism, using pot to determine variable domains
bool operator< (const _GHom &h) const
Ordering between _GHom. It is the chronological ordering of creation.
virtual void mark () const
For garbage collection. Used in first phase of garbage collection.
virtual GHom negate () const
returns a negation of a selector homomorphism h, such that h.negate() (d) = d - h(d)
Static Public Member Functions
static const _GHom * get_concret (const GHom &ghom)
Private Member Functions
GDDD eval_skip (const GDDD &) const
Private Attributes
int var1
int var2
comparator c
int refCounter
For garbage collection.
bool marking
For garbage collection.
bool immediat
For operation cache management.
size_t creation_counter
Counter of objects created (see constructors).
Constructor & Destructor Documentation
_VarCompVar()
_VarCompVar::_VarCompVar (int v1, comparator c, int v2) inline
Member Function Documentation
clone()
_GHom * _VarCompVar::clone () const inline virtual
Implements _GHom.
compose()
GHom _VarCompVar::compose (const GHom & other) const inline virtual
Todo:
other cases to be treated
Reimplemented from _GHom.
References c, _GHom::compose(), EQ, _GHom::get_concret(), LT, GDDD::null, var1, and var2.
eval()
GDDD StrongHom::eval (const GDDD & d) const virtual inherited
The evaluation mechanism of strong homomorphisms.
Evaluation is defined as :
Let an SDD d= (var, Union_i (val_i, d_i))
h (d) = Sum_i (phi(var, val_i) (d_i))
Implements _GHom.
References DED::add(), GDDD::begin(), GDDD::end(), GDDD::null, GDDD::one, StrongHom::phi(), StrongHom::phiOne(), GDDD::top, and GDDD::variable().
eval_skip()
GDDD _GHom::eval_skip (const GDDD & d) const private inherited
References GDDD::begin(), GDDD::end(), _GHom::eval(), GHom::id, GDDD::null, GDDD::one, _GHom::skip_variable(), GDDD::top, and GDDD::variable().
Referenced by GHom::eval().
get_concret()
static const _GHom * _GHom::get_concret (const GHom & ghom) inline static inherited
References GHom::concret.
Referenced by Add::Add(), addCompositionParameter(), _VarCompState::compose(), compose(), And::eval(), Fixpoint::eval(), Fixpoint::has_image(), Inter::skip_variable(), NotCond::skip_variable(), Add::skip_variable(), Monotonic::skip_variable(), Compose::skip_variable(), RightConcat::skip_variable(), and Fixpoint::skip_variable().
get_range()
const GHom::range_t _VarCompVar::get_range () const inline virtual
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
Reimplemented from _GHom.
References var1, and var2.
has_image()
GDDD StrongHom::has_image (const GDDD & d) const virtual inherited
Reimplemented from _GHom.
References GDDD::begin(), GDDD::end(), GDDD::null, GDDD::one, StrongHom::phi(), StrongHom::phiOne(), GDDD::top, and GDDD::variable().
has_image_skip()
GDDD _GHom::has_image_skip (const GDDD & d) const inherited
References GDDD::begin(), GDDD::end(), _GHom::has_image(), GHom::has_image(), GHom::id, GDDD::null, GDDD::one, _GHom::skip_variable(), GDDD::top, and GDDD::variable().
hash()
size_t _VarCompVar::hash () const inline virtual
Hash key computation.
It is essential for good hash table operation that the spread of the keys be as good as possible. Also, fast hash key computation is a good design goal. Note that bad hash functions will yield more collisions, thus equality comparisons which may be quite costly.
Implements _GHom.
References c, var1, and var2.
invert()
virtual GHom _GHom::invert (const GDDD &) const inline virtual inherited
returns the predescessor homomorphism, using pot to determine variable domains
Reimplemented in Identity, Constant, Apply2k, Mult, Inter, Add, Monotonic, Compose, And, Minus, Fixpoint, _setVarConst, and _incVar.
References _GHom::GHom, _GHom::is_selector(), GDDD::null, and _GHom::print().
Referenced by GHom::invert().
is_selector()
bool _VarCompVar::is_selector () const inline virtual
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
Reimplemented from _GHom.
mark()
virtual void _GHom::mark () const inline virtual inherited
For garbage collection. Used in first phase of garbage collection.
Reimplemented in Constant, Apply2k, Mult, Inter, NotCond, Add, Monotonic, Compose, And, LeftConcat, RightConcat, Minus, Fixpoint, and MLHomAdapter.
Referenced by GHom::mark().
negate()
GHom _GHom::negate () const virtual inherited
returns a negation of a selector homomorphism h, such that h.negate() (d) = d - h(d)
Reimplemented in Identity, Constant, Inter, NotCond, Add, And, and _VarCompState.
References _GHom::GHom.
Referenced by GHom::negate().
operator<()
bool _GHom::operator< (const _GHom & h) const inherited
Ordering between _GHom. It is the chronological ordering of creation.
References _GHom::creation_counter.
operator==() [1/2]
bool StrongHom::operator== (const _GHom & h) const virtual inherited
Comparator for unicity table.
Users should not use this. The behavior is to check for type mismatch (and return false if that is the case) or call specialized comparators of derived subclasses otherwise.
Implements _GHom.
operator==() [2/2]
bool _VarCompVar::operator== (const StrongHom & h) const inline virtual
Comparator is pure virtual. Define a behavior in user homomorphisms.
Implements StrongHom.
References c, var1, and var2.
phi()
GHom _VarCompVar::phi (int var, int val) const inline virtual
Evaluation over an arbitrary arc of a SDD.
Parameters
var the index of the variable labeling the node.
val the value labeling the arc.
Returns
a homomorphism to apply on the successor node
Implements StrongHom.
References c, _GHom::GHom, invertComp(), var1, var2, and varCompState().
phiOne()
GDDD _VarCompVar::phiOne () const inline virtual
Evaluation over terminal GDDD::one.
Returns a constant DDD. A homomorphism that does not overload phiOne does not expect to meet the terminal during it's evaluation, therefore default behavior returns GDDD::top
Reimplemented from StrongHom.
References GDDD::one.
print()
void _VarCompVar::print (std::ostream & os) const inline virtual
pretty print
Reimplemented from StrongHom.
References c, GDDD::getvarName(), to_string(), var1, and var2.
skip_variable()
bool _VarCompVar::skip_variable (int) const inline virtual
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
This is defined as a StrongHom with : phi(var,val) { if (skip_variable(var)) return GShom(var, val, this); else { real behavior } }
Reimplemented from _GHom.
References var1, and var2.
Member Data Documentation
c
comparator _VarCompVar::c private
Referenced by compose(), hash(), operator==(), phi(), and print().
creation_counter
size_t _GHom::creation_counter private inherited
Counter of objects created (see constructors).
This is used for the ordering between homomorphisms.
Referenced by _GHom::_GHom(), and _GHom::operator<().
immediat
bool _GHom::immediat mutable private inherited
For operation cache management.
If immediat==true, eval is called without attempting a cache hit. Currently only the constant homomorphism has this attribute set to true.
Referenced by GHom::operator()().
marking
bool _GHom::marking mutable private inherited
For garbage collection.
Used in the two phase garbage collection process. A Hom that is not marked after the first pass over the unicity table, will be sweeped in the second phase. Outside of garbage collection routine, marking should always bear the value false.
Referenced by GHom::garbage(), and GHom::mark().
refCounter
int _GHom::refCounter mutable private inherited
For garbage collection.
Counts the number of times a _GShom is referenced from the context of an Shom.
Referenced by Hom::Hom(), Hom::Hom(), Hom::Hom(), Hom::Hom(), Hom::operator=(), Hom::operator=(), GHom::refCounter(), and Hom::~Hom().
var1
int _VarCompVar::var1 private
Referenced by compose(), get_range(), hash(), operator==(), phi(), print(), and skip_variable().
var2
int _VarCompVar::var2 private
Referenced by compose(), get_range(), hash(), operator==(), phi(), print(), and skip_variable().
The documentation for this class was generated from the following file:
Hom_Basic.cpp
Please comment this page and report errors about it on the RefDocComments page.