DDD: MyNbStates Class Reference
MyNbStates Class Reference
Public Member Functions
MyNbStates (int v)
long double operator() (const GDDD &g)
Static Public Member Functions
static void clear ()
Private Types
typedef ext_hash_map< GDDD, long double > cache_type
Private Member Functions
long double nbStates (const GDDD &g)
Private Attributes
int val
Static Private Attributes
static cache_type cache = ext_hash_map<GDDD,long double> ()
Member Typedef Documentation
cache_type
typedef ext_hash_map<GDDD,long double> MyNbStates::cache_type private
Constructor & Destructor Documentation
MyNbStates()
MyNbStates::MyNbStates (int v) inline
Member Function Documentation
clear()
static void MyNbStates::clear () inline static
References cache, and ext_hash_map< Key, Data, HashKey, EqualKey >::clear().
Referenced by GDDD::garbage().
nbStates()
long double MyNbStates::nbStates (const GDDD & g) inline private
References GDDD::begin(), cache, ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::empty(), GDDD::end(), ext_hash_map< Key, Data, HashKey, EqualKey >::find(), ext_hash_map< Key, Data, HashKey, EqualKey >::insert(), nbStates(), GDDD::null, GDDD::one, GDDD::top, and val.
Referenced by nbStates(), and operator()().
operator()()
long double MyNbStates::operator() (const GDDD & g) inline
References nbStates().
Member Data Documentation
cache
ext_hash_map< GDDD, long double > MyNbStates::cache = ext_hash_map<GDDD,long double> () static private
Referenced by clear(), and nbStates().
val
int MyNbStates::val private
Referenced by nbStates().
The documentation for this class was generated from the following file:
DDD.cpp
Please comment this page and report errors about it on the RefDocComments page.