DDD: Fixpoint Class Reference
Fixpoint Class Reference
Public Member Functions
Fixpoint (const GHom &a, int ref=0, bool is_top_level=false)
bool operator== (const _GHom &h) const
Comparator.
size_t hash () const
Hash key computation.
_GHom * clone () const
bool skip_variable (int var) const
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
const GHom::range_t get_range () const
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
GHom invert (const GDDD &pot) const
returns the predescessor homomorphism, using pot to determine variable domains
bool is_selector () const
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
GDDD has_image (const GDDD &d) const
GDDD eval (const GDDD &d) const
The computation function responsible for evaluation over a node.
void mark () const
For garbage collection. Used in first phase of garbage collection.
void print (std::ostream &os) const
GDDD has_image_skip (const GDDD &) const
bool operator< (const _GHom &h) const
Ordering between _GHom. It is the chronological ordering of creation.
virtual GHom negate () const
returns a negation of a selector homomorphism h, such that h.negate() (d) = d - h(d)
virtual GHom compose (const GHom &r) const
Static Public Member Functions
static const _GHom * get_concret (const GHom &ghom)
Private Member Functions
GDDD eval_skip (const GDDD &) const
Private Attributes
GHom arg
bool can_garbage
int refCounter
For garbage collection.
bool marking
For garbage collection.
bool immediat
For operation cache management.
size_t creation_counter
Counter of objects created (see constructors).
Constructor & Destructor Documentation
Fixpoint()
Fixpoint::Fixpoint (const GHom & a, int ref = 0, bool is_top_level = false) inline
Referenced by clone().
Member Function Documentation
clone()
_GHom* Fixpoint::clone () const inline virtual
Implements _GHom.
References Fixpoint().
compose()
GHom _GHom::compose (const GHom & r) const virtual inherited
Reimplemented in _VarCompVar, and _VarCompState.
References GHom::id, and GDDD::null.
Referenced by _VarCompState::compose(), _VarCompVar::compose(), and GHom::compose().
eval()
GDDD Fixpoint::eval (const GDDD &) const inline virtual
The computation function responsible for evaluation over a node.
Users should not directly use this. Normal behavior is to use GShom::operator() that encapsulates this call with operation caching.
Implements _GHom.
References DED::add(), arg, can_garbage, fixpoint(), MemoryManager::garbage(), _GHom::get_concret(), fobs::get_fixobserver(), _GHom::Hom, GDDD::mark(), GHom::mark(), GDDD::null, GDDD::one, MemoryManager::should_garbage(), testShouldInterrupt(), testWasInterrupt(), GDDD::top, and GDDD::variable().
eval_skip()
GDDD _GHom::eval_skip (const GDDD & d) const private inherited
References GDDD::begin(), GDDD::end(), _GHom::eval(), GHom::id, GDDD::null, GDDD::one, _GHom::skip_variable(), GDDD::top, and GDDD::variable().
Referenced by GHom::eval().
get_concret()
static const _GHom* _GHom::get_concret (const GHom & ghom) inline static inherited
References GHom::concret.
Referenced by Add::Add(), addCompositionParameter(), _VarCompState::compose(), _VarCompVar::compose(), And::eval(), eval(), has_image(), Inter::skip_variable(), NotCond::skip_variable(), Add::skip_variable(), Monotonic::skip_variable(), Compose::skip_variable(), RightConcat::skip_variable(), and skip_variable().
get_range()
const GHom::range_t Fixpoint::get_range () const inline virtual
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
Reimplemented from _GHom.
References arg, and GHom::get_range().
has_image()
GDDD Fixpoint::has_image (const GDDD & d) const inline virtual
Reimplemented from _GHom.
References DED::add(), arg, can_garbage, fixpoint(), _GHom::get_concret(), _GHom::has_image(), GHom::has_image(), GHom::id, GDDD::null, GDDD::one, GDDD::top, and GDDD::variable().
has_image_skip()
GDDD _GHom::has_image_skip (const GDDD & d) const inherited
References GDDD::begin(), GDDD::end(), _GHom::has_image(), GHom::has_image(), GHom::id, GDDD::null, GDDD::one, _GHom::skip_variable(), GDDD::top, and GDDD::variable().
hash()
size_t Fixpoint::hash () const inline virtual
Hash key computation.
It is essential for good hash table operation that the spread of the keys be as good as possible. Also, fast hash key computation is a good design goal. Note that bad hash functions will yield more collisions, thus equality comparisons which may be quite costly.
Implements _GHom.
References arg, and GHom::hash().
invert()
GHom Fixpoint::invert (const GDDD &) const inline virtual
returns the predescessor homomorphism, using pot to determine variable domains
Reimplemented from _GHom.
References arg, fixpoint(), GHom::id, and GHom::invert().
is_selector()
bool Fixpoint::is_selector () const inline virtual
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
Reimplemented from _GHom.
References arg, and GHom::is_selector().
mark()
void Fixpoint::mark () const inline virtual
For garbage collection. Used in first phase of garbage collection.
Reimplemented from _GHom.
References arg, and GHom::mark().
negate()
GHom _GHom::negate () const virtual inherited
returns a negation of a selector homomorphism h, such that h.negate() (d) = d - h(d)
Reimplemented in _VarCompState, And, Add, NotCond, Inter, Constant, and Identity.
References _GHom::GHom.
Referenced by GHom::negate().
operator<()
bool _GHom::operator< (const _GHom & h) const inherited
Ordering between _GHom. It is the chronological ordering of creation.
References _GHom::creation_counter.
operator==()
bool Fixpoint::operator== (const _GHom & h) const inline virtual
Comparator.
Used in case of hash collision. Should be appropriately defined in derived classes, in particular in user defined homomorphisms.
Implements _GHom.
References arg.
print()
void Fixpoint::print (std::ostream & os) const inline virtual
Implements _GHom.
References arg.
skip_variable()
bool Fixpoint::skip_variable (int) const inline virtual
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
This is defined as a StrongHom with : phi(var,val) { if (skip_variable(var)) return GShom(var, val, this); else { real behavior } }
Reimplemented from _GHom.
References arg, _GHom::get_concret(), and _GHom::skip_variable().
Member Data Documentation
arg
GHom Fixpoint::arg private
Referenced by eval(), get_range(), has_image(), hash(), invert(), is_selector(), mark(), operator==(), print(), and skip_variable().
can_garbage
bool Fixpoint::can_garbage private
Referenced by eval(), and has_image().
creation_counter
size_t _GHom::creation_counter private inherited
Counter of objects created (see constructors).
This is used for the ordering between homomorphisms.
Referenced by _GHom::_GHom(), and _GHom::operator<().
immediat
bool _GHom::immediat mutable private inherited
For operation cache management.
If immediat==true, eval is called without attempting a cache hit. Currently only the constant homomorphism has this attribute set to true.
Referenced by GHom::operator()().
marking
bool _GHom::marking mutable private inherited
For garbage collection.
Used in the two phase garbage collection process. A Hom that is not marked after the first pass over the unicity table, will be sweeped in the second phase. Outside of garbage collection routine, marking should always bear the value false.
Referenced by GHom::garbage(), and GHom::mark().
refCounter
int _GHom::refCounter mutable private inherited
For garbage collection.
Counts the number of times a _GShom is referenced from the context of an Shom.
Referenced by Hom::Hom(), Hom::operator=(), GHom::refCounter(), and Hom::~Hom().
The documentation for this class was generated from the following file:
Hom.cpp
Please comment this page and report errors about it on the RefDocComments page.