DDD: SddSize Class Reference
SddSize Class Reference
Public Member Functions
SddSize ()
unsigned long int operator() (const GSDD &g)
Public Attributes
unsigned long int res
unsigned long int d3res
Private Member Functions
void sddsize (const GSDD &g)
void sddsize (const DataSet *g)
void sddsize (const GDDD &g)
Private Attributes
bool firstError
d3::set< GSDD >::type s
d3::set< GDDD >::type sd3
Constructor & Destructor Documentation
SddSize()
SddSize::SddSize () inline
Member Function Documentation
operator()()
unsigned long int SddSize::operator() (const GSDD & g) inline
References d3res, res, s, sd3, and sddsize().
sddsize() [1/3]
void SddSize::sddsize (const DataSet * g) inline private
References firstError, and sddsize().
sddsize() [2/3]
void SddSize::sddsize (const GDDD & g) inline private
References GDDD::begin(), d3res, GDDD::end(), sd3, and sddsize().
sddsize() [3/3]
void SddSize::sddsize (const GSDD & g) inline private
References GSDD::begin(), GSDD::end(), res, s, and sddsize().
Referenced by operator()(), sddsize(), sddsize(), and sddsize().
Member Data Documentation
d3res
unsigned long int SddSize::d3res
Referenced by GSDD::node_size(), operator()(), and sddsize().
firstError
bool SddSize::firstError private
Referenced by sddsize().
res
unsigned long int SddSize::res
Referenced by GSDD::node_size(), operator()(), and sddsize().
s
d3::set<GSDD>::type SddSize::s private
Referenced by operator()(), and sddsize().
sd3
d3::set<GDDD>::type SddSize::sd3 private
Referenced by operator()(), and sddsize().
The documentation for this class was generated from the following file:
SDD.cpp
Please comment this page and report errors about it on the RefDocComments page.