DDD: _SDED_Concat Class Reference
_SDED_Concat Class Reference
Public Member Functions
size_t hash () const
bool operator== (const _SDED &e) const
_SDED * clone () const
GSDD eval () const
~_SDED_Concat ()
Static Public Member Functions
static GSDD create (const GSDD &g1, const GSDD &g2)
Public Attributes
GSDD result
Private Member Functions
_SDED_Concat (const GSDD &g1, const GSDD &g2)
Private Attributes
GSDD parameter1
GSDD parameter2
Constructor & Destructor Documentation
_SDED_Concat()
_SDED_Concat::_SDED_Concat (const GSDD & g1, const GSDD & g2) inline private
Referenced by clone(), and create().
~_SDED_Concat()
_SDED_Concat::~_SDED_Concat () inline
Member Function Documentation
clone()
_SDED* _SDED_Concat::clone () const inline virtual
Implements _SDED.
References _SDED_Concat().
create()
GSDD _SDED_Concat::create (const GSDD & g1, const GSDD & g2) static
References _SDED_Concat(), compute(), GSDD::null, GSDD::one, and GSDD::top.
Referenced by operator^().
eval()
GSDD _SDED_Concat::eval () const virtual
Implements _SDED.
References GSDD::begin(), GSDD::end(), GSDD::null, parameter1, parameter2, square_union(), and GSDD::variable().
hash()
size_t _SDED_Concat::hash () const virtual
Implements _SDED.
References GSDD::hash(), parameter1, and parameter2.
operator==()
bool _SDED_Concat::operator== (const _SDED & e) const virtual
Implements _SDED.
References parameter1, and parameter2.
Member Data Documentation
parameter1
GSDD _SDED_Concat::parameter1 private
Referenced by eval(), hash(), and operator==().
parameter2
GSDD _SDED_Concat::parameter2 private
Referenced by eval(), hash(), and operator==().
result
GSDD _SDED::result inherited
The documentation for this class was generated from the following file:
SDED.cpp
Please comment this page and report errors about it on the RefDocComments page.