DDD: UniqueTable< T > Class Template Reference
UniqueTable< T > Class Template Reference
This class implements a unicity table mechanism, based on an STL hash_set.
#include <UniqueTable.h>
Public Types
typedef d3::hash_set< constT * >::type Table
Typedef helps hide implementation type (currently gnu gcc's hash_set).
Public Member Functions
UniqueTable ()
Constructor, builds a default table.
UniqueTable (size_t s)
const T * operator() (const T &_g)
The application operator, returns the address of the value already in the table if it exists, or inserts and returns the address of the value inserted.
size_t size () const
Returns the current number of filled entries in the table.
Public Attributes
Table table
The actual table, operations on the UniqueTable are delegated on this.
Detailed Description
template<typename T>
class UniqueTable< T >
This class implements a unicity table mechanism, based on an STL hash_set.
Requirements on the contained type are thus those of hash_set.
Member Typedef Documentation
Table
template<typename T > typedef d3::hash_set<constT*>::type UniqueTable< T >::Table
Typedef helps hide implementation type (currently gnu gcc's hash_set).
Constructor & Destructor Documentation
UniqueTable() [1/2]
template<typename T > UniqueTable< T >::UniqueTable () inline
Constructor, builds a default table.
References UniqueTable< T >::table.
UniqueTable() [2/2]
template<typename T > UniqueTable< T >::UniqueTable (size_t s) inline
References UniqueTable< T >::table.
Member Function Documentation
operator()()
template<typename T > const T * UniqueTable< T >::operator() (const T & _g) inline
The application operator, returns the address of the value already in the table if it exists, or inserts and returns the address of the value inserted.
Parameters
_g the pointer to the value we want to find in the table.
Returns
the address of an object stored in the UniqueTable such that (*_g == *return_value)
References UniqueTable< T >::table.
size()
template<typename T > size_t UniqueTable< T >::size () const inline
Returns the current number of filled entries in the table.
References UniqueTable< T >::table.
Referenced by DED::garbage(), SDED::garbage(), SDED::peak(), DED::pstats(), and SDED::statistics().
Member Data Documentation
table
template<typename T > Table UniqueTable< T >::table
The actual table, operations on the UniqueTable are delegated on this.
Referenced by DED::garbage(), IntDataSet::garbage(), SDED::garbage(), UniqueTable< T >::operator()(), DED::peak(), UniqueTable< T >::size(), DED::statistics(), UniqueTable< T >::UniqueTable(), and UniqueTable< T >::UniqueTable().
The documentation for this class was generated from the following file:
UniqueTable.h
Please comment this page and report errors about it on the RefDocComments page.