DDD: Statistic Class Reference
Statistic Class Reference
#include <statistic.hpp>
Public Member Functions
Statistic (const SDD &s, const std::string &name, OutputType style=LATEX, bool show_peak=true)
Create a statistic for the current SDD s, style LATEX by default.
Statistic (const DDD &s, const std::string &name, OutputType style=LATEX, bool show_peak=true)
Create a statistic for the current DDD s, style LATEX by default.
void print_header (std::ostream &os)
Print column headers, using current style.
void print_trailer (std::ostream &os, bool withLegend=true)
Print trailer.
void print_line (std::ostream &os)
Print a line for current statistic.
void print_table (std::ostream &os)
Convenience print a table.
void print_legend (std::ostream &os)
Print a legend to the table.
void setStyle (OutputType style)
Setter for style.
double getTime () const
Accessors.
long double getNbStates () const
Private Member Functions
void load (const SDD &s)
load from a SDD
void load (const DDD &s)
load from a DDD
Private Attributes
long double nb_Stat
number of final states
long double DDD_size
number of final DDD nodes
long double SDD_size
number of final SDD nodes
long double DDD_peak_size
peak DDD unicity table size
long double SDD_peak_size
peak DDD unicity table size
double total_time
total time
size_t memory
resident mem (kb)
double nbHom
Hom final.
double nbShom
SHom final.
double ddd_cache
DDD cache.
double sdd_cache
SDD cache peak.
bool isPureDDD
Mode : include SDD or not.
OutputType style
Mode : outputType.
std::string stat_name
Name of this statistic.
size_t shom_cache
Size of SHom cache.
bool show_peak
show peak
Constructor & Destructor Documentation
Statistic() [1/2]
Statistic::Statistic (const SDD & s, const std::string & name, OutputType style = LATEX, bool show_peak = true)
Create a statistic for the current SDD s, style LATEX by default.
The statistic is sampled and stored, this call triggers SDD mode (more columns).
Parameters
s the SDD used for final node and state count.
name the row name (first column)
style use LATEX for formatted latex table or CSV to import in excel or gnumeric.
show_peak if you want to show peak size instead of current size for caches
References load().
Statistic() [2/2]
Statistic::Statistic (const DDD & s, const std::string & name, OutputType style = LATEX, bool show_peak = true)
Create a statistic for the current DDD s, style LATEX by default.
The statistic is sampled and stored, this call triggers DDD mode (less columns).
Parameters
s the DDD used for final node and state count.
name the row name (first column)
style use LATEX for formatted latex table or CSV to import in excel or gnumeric.
show_peak if you want to show peak size instead of current size for caches
References load().
Member Function Documentation
getNbStates()
long double Statistic::getNbStates () const inline
References nb_Stat.
getTime()
double Statistic::getTime () const inline
Accessors.
References total_time.
load() [1/2]
void Statistic::load (const DDD & s) private
load from a DDD
References ddd_cache, DDD_peak_size, DDD_size, process::getResidentMemory(), process::getTotalTime(), memory, nb_Stat, nbHom, GDDD::nbStates(), GDDD::peak(), DED::peak(), show_peak, GDDD::size(), DED::statistics(), GHom::statistics(), and total_time.
load() [2/2]
void Statistic::load (const SDD & s) private
load from a SDD
References GShom::cache_size(), ddd_cache, DDD_peak_size, DDD_size, process::getResidentMemory(), process::getTotalTime(), memory, nb_Stat, nbHom, nbShom, GSDD::nbStates(), GSDD::node_size(), GDDD::peak(), DED::peak(), GSDD::peak(), SDED::peak(), sdd_cache, SDD_peak_size, SDD_size, shom_cache, show_peak, DED::statistics(), GHom::statistics(), SDED::statistics(), GShom::statistics(), and total_time.
Referenced by Statistic(), and Statistic().
print_header()
void Statistic::print_header (std::ostream & os)
Print column headers, using current style.
For latex this also outputs a header (\begin document etc...).
References isPureDDD, LATEX, line_sep, show_peak, style, and value_sep.
Referenced by print_table().
print_legend()
void Statistic::print_legend (std::ostream & os)
Print a legend to the table.
give interpretation for row headers
References isPureDDD, line_sep, show_peak, and style.
print_line()
void Statistic::print_line (std::ostream & os)
Print a line for current statistic.
To produce tables call print_header once then print_line for all your statistics.
References ddd_cache, DDD_peak_size, DDD_size, isPureDDD, line_sep, memory, nb_Stat, nbHom, nbShom, sdd_cache, SDD_peak_size, SDD_size, shom_cache, stat_name, style, total_time, and value_sep.
Referenced by print_table().
print_table()
void Statistic::print_table (std::ostream & os)
Convenience print a table.
Useful if you have a single stat to show. Calls print_header,print_line,print_trailer in this order.
References print_header(), print_line(), and print_trailer().
print_trailer()
void Statistic::print_trailer (std::ostream & os, bool withLegend = true)
Print trailer.
The trailer includes a key to reading the columns. In latex mode it also closes the document.
References LATEX, and style.
Referenced by print_table().
setStyle()
void Statistic::setStyle (OutputType style)
Setter for style.
Member Data Documentation
ddd_cache
double Statistic::ddd_cache private
DDD cache.
Referenced by load(), load(), and print_line().
DDD_peak_size
long double Statistic::DDD_peak_size private
peak DDD unicity table size
Referenced by load(), load(), and print_line().
DDD_size
long double Statistic::DDD_size private
number of final DDD nodes
Referenced by load(), load(), and print_line().
isPureDDD
bool Statistic::isPureDDD private
Mode : include SDD or not.
Referenced by print_header(), print_legend(), and print_line().
memory
size_t Statistic::memory private
resident mem (kb)
Referenced by load(), load(), and print_line().
nb_Stat
long double Statistic::nb_Stat private
number of final states
Referenced by getNbStates(), load(), load(), and print_line().
nbHom
double Statistic::nbHom private
Hom final.
Referenced by load(), load(), and print_line().
nbShom
double Statistic::nbShom private
SHom final.
Referenced by load(), and print_line().
sdd_cache
double Statistic::sdd_cache private
SDD cache peak.
Referenced by load(), and print_line().
SDD_peak_size
long double Statistic::SDD_peak_size private
peak DDD unicity table size
Referenced by load(), and print_line().
SDD_size
long double Statistic::SDD_size private
number of final SDD nodes
Referenced by load(), and print_line().
shom_cache
size_t Statistic::shom_cache private
Size of SHom cache.
Referenced by load(), and print_line().
show_peak
bool Statistic::show_peak private
show peak
Referenced by load(), load(), print_header(), and print_legend().
stat_name
std::string Statistic::stat_name private
Name of this statistic.
Referenced by print_line().
style
OutputType Statistic::style private
Mode : outputType.
Referenced by print_header(), print_legend(), print_line(), and print_trailer().
total_time
double Statistic::total_time private
total time
Referenced by getTime(), load(), load(), and print_line().
The documentation for this class was generated from the following files:
statistic.hpp
statistic.cpp
Please comment this page and report errors about it on the RefDocComments page.