DDD: nsMLShom::ConstantUp Class Reference
nsMLShom::ConstantUp Class Reference
Public Member Functions
ConstantUp (const GShom &uup, const MLShom &ddown)
bool operator== (const _MLShom &other) const
_MLShom * clone () const
size_t hash () const
unique table trivia
bool skip_variable (int) const
SHomNodeMap eval (const GSDD &d) const
virtual bool shouldCache () const
test if caching should be done : default means should cache
Private Member Functions
virtual void mark () const
For garbage collection. Used in first phase of garbage collection.
Private Attributes
GShom up
MLShom down
int refCounter
For garbage collection.
bool marking
For garbage collection.
Constructor & Destructor Documentation
ConstantUp()
nsMLShom::ConstantUp::ConstantUp (const GShom & uup, const MLShom & ddown) inline
Referenced by clone().
Member Function Documentation
clone()
_MLShom* nsMLShom::ConstantUp::clone () const inline virtual
Implements _MLShom.
References ConstantUp().
eval()
SHomNodeMap nsMLShom::ConstantUp::eval (const GSDD & d) const inline virtual
Implements _MLShom.
References AdditiveMap< K, V, EqualKey >::add(), AdditiveMap< K, V, EqualKey >::begin(), down, AdditiveMap< K, V, EqualKey >::end(), and up.
hash()
size_t nsMLShom::ConstantUp::hash () const inline virtual
unique table trivia
Implements _MLShom.
References down, MLShom::hash(), GShom::hash(), and up.
mark()
virtual void _MLShom::mark () const inline private virtual inherited
For garbage collection. Used in first phase of garbage collection.
operator==()
bool nsMLShom::ConstantUp::operator== (const _MLShom & other) const inline virtual
Implements _MLShom.
References down, and up.
shouldCache()
virtual bool _MLShom::shouldCache () const inline virtual inherited
test if caching should be done : default means should cache
Reimplemented in nsMLShom::Identity.
skip_variable()
bool nsMLShom::ConstantUp::skip_variable (int) const inline
Member Data Documentation
down
MLShom nsMLShom::ConstantUp::down private
Referenced by eval(), hash(), and operator==().
marking
bool _MLShom::marking mutable private inherited
For garbage collection.
Used in the two phase garbage collection process. A Shom that is not marked after the first pass over the unicity table, will be sweeped in the second phase. Outside of garbage collection routine, marking should always bear the value false.
Referenced by MLShom::garbage().
refCounter
int _MLShom::refCounter mutable private inherited
For garbage collection.
Counts the number of times a _MLHom is referenced from the context of an MLHom.
up
GShom nsMLShom::ConstantUp::up private
Referenced by eval(), hash(), and operator==().
The documentation for this class was generated from the following file:
MLSHom.cpp
Please comment this page and report errors about it on the RefDocComments page.