DDD: StrongMLShom Class Reference
StrongMLShom Class Reference abstract
#include <MLSHom.h>
Public Member Functions
bool operator== (const _MLShom &h) const
virtual bool operator== (const StrongMLShom &) const =0
SHomNodeMap eval (const GSDD &) const
virtual SHomHomMap phi (int var, const DataSet &val) const =0
User defined behavior is input through this function.
virtual SHomNodeMap phiOne () const =0
virtual bool shouldCache () const
test if caching should be done : default means should cache
virtual size_t hash () const =0
unique table trivia
virtual _MLShom * clone () const =0
Private Member Functions
virtual void mark () const
For garbage collection. Used in first phase of garbage collection.
Private Attributes
int refCounter
For garbage collection.
bool marking
For garbage collection.
Member Function Documentation
clone()
virtual _MLShom* _MLShom::clone () const pure virtual inherited
Implemented in nsMLShom::LeftConcat, nsMLShom::ConstantUp, nsMLShom::GShomAdapter, nsMLShom::Add, and nsMLShom::Identity.
eval()
SHomNodeMap StrongMLShom::eval (const GSDD & d) const virtual
Implements _MLShom.
References AdditiveMap< K, V, EqualKey >::add(), AdditiveMap< K, V, EqualKey >::begin(), GSDD::begin(), AdditiveMap< K, V, EqualKey >::end(), GSDD::end(), GShom::id, GSDD::null, GSDD::one, phi(), phiOne(), GSDD::top, and GSDD::variable().
hash()
virtual size_t _MLShom::hash () const pure virtual inherited
unique table trivia
Implemented in nsMLShom::LeftConcat, nsMLShom::ConstantUp, nsMLShom::GShomAdapter, nsMLShom::Add, and nsMLShom::Identity.
mark()
virtual void _MLShom::mark () const inline private virtual inherited
For garbage collection. Used in first phase of garbage collection.
operator==() [1/2]
bool StrongMLShom::operator== (const _MLShom & h) const virtual
Implements _MLShom.
operator==() [2/2]
virtual bool StrongMLShom::operator== (const StrongMLShom &) const pure virtual
phi()
virtual SHomHomMap StrongMLShom::phi (int var, const DataSet & val) const pure virtual
User defined behavior is input through this function.
Referenced by eval().
phiOne()
virtual SHomNodeMap StrongMLShom::phiOne () const pure virtual
Referenced by eval().
shouldCache()
virtual bool _MLShom::shouldCache () const inline virtual inherited
test if caching should be done : default means should cache
Reimplemented in nsMLShom::Identity.
Member Data Documentation
marking
bool _MLShom::marking mutable private inherited
For garbage collection.
Used in the two phase garbage collection process. A Shom that is not marked after the first pass over the unicity table, will be sweeped in the second phase. Outside of garbage collection routine, marking should always bear the value false.
Referenced by MLShom::garbage().
refCounter
int _MLShom::refCounter mutable private inherited
For garbage collection.
Counts the number of times a _MLHom is referenced from the context of an MLHom.
The documentation for this class was generated from the following files:
MLSHom.h
MLSHom.cpp
Please comment this page and report errors about it on the RefDocComments page.