DDD: nsMLShom::GShomAdapter Class Reference
nsMLShom::GShomAdapter Class Reference
Public Member Functions
GShomAdapter (const GShom &_h, int ref=0)
bool operator== (const _MLShom &other) const
size_t hash () const
unique table trivia
_MLShom * clone () const
bool skip_variable (int var) const
SHomNodeMap eval (const GSDD &d) const
virtual bool shouldCache () const
test if caching should be done : default means should cache
Private Member Functions
virtual void mark () const
For garbage collection. Used in first phase of garbage collection.
Private Attributes
GShom h
int refCounter
For garbage collection.
bool marking
For garbage collection.
Constructor & Destructor Documentation
GShomAdapter()
nsMLShom::GShomAdapter::GShomAdapter (const GShom & _h, int ref = 0) inline
Member Function Documentation
clone()
_MLShom * nsMLShom::GShomAdapter::clone () const inline virtual
Implements _MLShom.
eval()
SHomNodeMap nsMLShom::GShomAdapter::eval (const GSDD & d) const inline virtual
Implements _MLShom.
References AdditiveMap< K, V, EqualKey >::add(), h, and GShom::id.
hash()
size_t nsMLShom::GShomAdapter::hash () const inline virtual
unique table trivia
Implements _MLShom.
References h, and GShom::hash().
mark()
virtual void _MLShom::mark () const inline private virtual inherited
For garbage collection. Used in first phase of garbage collection.
operator==()
bool nsMLShom::GShomAdapter::operator== (const _MLShom & other) const inline virtual
Implements _MLShom.
References h.
shouldCache()
virtual bool _MLShom::shouldCache () const inline virtual inherited
test if caching should be done : default means should cache
Reimplemented in nsMLShom::Identity.
skip_variable()
bool nsMLShom::GShomAdapter::skip_variable (int var) const inline
References h, and GShom::skip_variable().
Member Data Documentation
h
GShom nsMLShom::GShomAdapter::h private
Referenced by eval(), hash(), operator==(), and skip_variable().
marking
bool _MLShom::marking mutable private inherited
For garbage collection.
Used in the two phase garbage collection process. A Shom that is not marked after the first pass over the unicity table, will be sweeped in the second phase. Outside of garbage collection routine, marking should always bear the value false.
Referenced by MLShom::garbage().
refCounter
int _MLShom::refCounter mutable private inherited
For garbage collection.
Counts the number of times a _MLHom is referenced from the context of an MLHom.
The documentation for this class was generated from the following file:
MLSHom.cpp
Please comment this page and report errors about it on the RefDocComments page.