DDD: MLCache< MLHomType, NodeType, HomNodeMapType > Class Template Reference
MLCache< MLHomType, NodeType, HomNodeMapType > Class Template Reference
#include <MLCache.hh>
Public Member Functions
MLCache ()
void clear (bool keepstats=false)
clear the cache, discarding all values.
size_t peak () const
size_t size () const
std::pair< bool, HomNodeMapType > insert (const MLHomType &hom, const NodeType &node)
Private Types
typedef hash_map< std::pair< MLHomType, NodeType >, HomNodeMapType >::type hash_map
Private Attributes
size_t peak_
hash_map cache_
Member Typedef Documentation
hash_map
template<typename MLHomType , typename NodeType , typename HomNodeMapType > typedef hash_map<std::pair<MLHomType,NodeType>,HomNodeMapType>::type MLCache< MLHomType, NodeType, HomNodeMapType >::hash_map private
Constructor & Destructor Documentation
MLCache()
template<typename MLHomType , typename NodeType , typename HomNodeMapType > MLCache< MLHomType, NodeType, HomNodeMapType >::MLCache () inline
Member Function Documentation
clear()
template<typename MLHomType , typename NodeType , typename HomNodeMapType > void MLCache< MLHomType, NodeType, HomNodeMapType >::clear (bool keepstats = false) inline
clear the cache, discarding all values.
References MLCache< MLHomType, NodeType, HomNodeMapType >::cache_, ext_hash_map< Key, Data, HashKey, EqualKey >::clear(), and MLCache< MLHomType, NodeType, HomNodeMapType >::peak().
Referenced by MLHom::garbage().
insert()
template<typename MLHomType , typename NodeType , typename HomNodeMapType > std::pair< bool, HomNodeMapType > MLCache< MLHomType, NodeType, HomNodeMapType >::insert (const MLHomType & hom, const NodeType & node) inline
References MLCache< MLHomType, NodeType, HomNodeMapType >::cache_, ext_hash_map< Key, Data, HashKey, EqualKey >::find(), and ext_hash_map< Key, Data, HashKey, EqualKey >::insert().
Referenced by MLHom::operator()().
peak()
template<typename MLHomType , typename NodeType , typename HomNodeMapType > size_t MLCache< MLHomType, NodeType, HomNodeMapType >::peak () const inline
References MLCache< MLHomType, NodeType, HomNodeMapType >::peak_, and MLCache< MLHomType, NodeType, HomNodeMapType >::size().
Referenced by MLCache< MLHomType, NodeType, HomNodeMapType >::clear().
size()
template<typename MLHomType , typename NodeType , typename HomNodeMapType > size_t MLCache< MLHomType, NodeType, HomNodeMapType >::size () const inline
References MLCache< MLHomType, NodeType, HomNodeMapType >::cache_, and ext_hash_map< Key, Data, HashKey, EqualKey >::size().
Referenced by MLCache< MLHomType, NodeType, HomNodeMapType >::peak().
Member Data Documentation
cache_
template<typename MLHomType , typename NodeType , typename HomNodeMapType > hash_map MLCache< MLHomType, NodeType, HomNodeMapType >::cache_ private
Referenced by MLCache< MLHomType, NodeType, HomNodeMapType >::clear(), MLCache< MLHomType, NodeType, HomNodeMapType >::insert(), and MLCache< MLHomType, NodeType, HomNodeMapType >::size().
peak_
template<typename MLHomType , typename NodeType , typename HomNodeMapType > size_t MLCache< MLHomType, NodeType, HomNodeMapType >::peak_ mutable private
Referenced by MLCache< MLHomType, NodeType, HomNodeMapType >::peak().
The documentation for this class was generated from the following file:
MLCache.hh
Please comment this page and report errors about it on the RefDocComments page.