DDD: Add Class Reference
Add Class Reference
Public Types
typedef std::vector< GHom > param_t
typedef param_t::const_iterator param_it
typedef std::pair< GHom, std::set< GHom > > partition
typedef std::map< int, partition > partition_cache_type
Public Member Functions
Add (const std::set< GHom > &param, int ref=0)
bool get_have_id () const
GHom negate () const
returns a negation of a selector homomorphism h, such that h.negate() (d) = d - h(d)
GDDD has_image (const GDDD &d) const
param_t & get_parameters ()
const GHom::range_t get_range () const
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
partition get_partition (int var) const
GHom invert (const GDDD &pot) const
returns the predescessor homomorphism, using pot to determine variable domains
bool operator== (const _GHom &h) const
Comparator.
size_t hash () const
Hash key computation.
bool is_selector () const
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
_GHom * clone () const
bool skip_variable (int var) const
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
GDDD eval (const GDDD &d) const
The computation function responsible for evaluation over a node.
void mark () const
For garbage collection. Used in first phase of garbage collection.
void print (std::ostream &os) const
GDDD has_image_skip (const GDDD &) const
bool operator< (const _GHom &h) const
Ordering between _GHom. It is the chronological ordering of creation.
virtual GHom compose (const GHom &r) const
Static Public Member Functions
static const _GHom * get_concret (const GHom &ghom)
Public Attributes
param_t parameters
partition_cache_type partition_cache
bool have_id
Private Member Functions
GDDD eval_skip (const GDDD &) const
Private Attributes
int refCounter
For garbage collection.
bool marking
For garbage collection.
bool immediat
For operation cache management.
size_t creation_counter
Counter of objects created (see constructors).
Member Typedef Documentation
param_it
typedef param_t::const_iterator Add::param_it
param_t
typedef std::vector<GHom> Add::param_t
partition
typedef std::pair< GHom , std::set<GHom> > Add::partition
partition_cache_type
typedef std::map<int,partition> Add::partition_cache_type
Constructor & Destructor Documentation
Add()
Add::Add (const std::set< GHom > & param, int ref = 0) inline
References _GHom::get_concret(), and parameters.
Member Function Documentation
clone()
_GHom * Add::clone () const inline virtual
Implements _GHom.
compose()
GHom _GHom::compose (const GHom & r) const virtual inherited
Reimplemented in _VarCompState, and _VarCompVar.
References GHom::id, and GDDD::null.
Referenced by _VarCompState::compose(), _VarCompVar::compose(), and GHom::compose().
eval()
GDDD Add::eval (const GDDD &) const inline virtual
The computation function responsible for evaluation over a node.
Users should not directly use this. Normal behavior is to use GShom::operator() that encapsulates this call with operation caching.
Implements _GHom.
References DED::add(), GDDD::null, GDDD::one, parameters, partition_cache, skip_variable(), GDDD::top, and GDDD::variable().
eval_skip()
GDDD _GHom::eval_skip (const GDDD & d) const private inherited
References GDDD::begin(), GDDD::end(), _GHom::eval(), GHom::id, GDDD::null, GDDD::one, _GHom::skip_variable(), GDDD::top, and GDDD::variable().
Referenced by GHom::eval().
get_concret()
static const _GHom * _GHom::get_concret (const GHom & ghom) inline static inherited
References GHom::concret.
Referenced by Add(), addCompositionParameter(), _VarCompState::compose(), _VarCompVar::compose(), And::eval(), Fixpoint::eval(), Fixpoint::has_image(), Inter::skip_variable(), NotCond::skip_variable(), skip_variable(), Monotonic::skip_variable(), Compose::skip_variable(), RightConcat::skip_variable(), and Fixpoint::skip_variable().
get_have_id()
bool Add::get_have_id () const inline
References GHom::id, and parameters.
get_parameters()
param_t & Add::get_parameters () inline
References parameters.
get_partition()
partition Add::get_partition (int var) const inline
References partition_cache, and skip_variable().
get_range()
const GHom::range_t Add::get_range () const inline virtual
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
Reimplemented from _GHom.
References parameters.
has_image()
GDDD Add::has_image (const GDDD & d) const inline virtual
Reimplemented from _GHom.
References GHom::has_image(), GDDD::null, GDDD::one, parameters, partition_cache, skip_variable(), GDDD::top, and GDDD::variable().
has_image_skip()
GDDD _GHom::has_image_skip (const GDDD & d) const inherited
References GDDD::begin(), GDDD::end(), _GHom::has_image(), GHom::has_image(), GHom::id, GDDD::null, GDDD::one, _GHom::skip_variable(), GDDD::top, and GDDD::variable().
hash()
size_t Add::hash () const inline virtual
Hash key computation.
It is essential for good hash table operation that the spread of the keys be as good as possible. Also, fast hash key computation is a good design goal. Note that bad hash functions will yield more collisions, thus equality comparisons which may be quite costly.
Implements _GHom.
References parameters.
invert()
GHom Add::invert (const GDDD &) const inline virtual
returns the predescessor homomorphism, using pot to determine variable domains
Reimplemented from _GHom.
References GHom::add(), and parameters.
is_selector()
bool Add::is_selector () const inline virtual
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
Reimplemented from _GHom.
References parameters.
mark()
void Add::mark () const inline virtual
For garbage collection. Used in first phase of garbage collection.
Reimplemented from _GHom.
References parameters, and partition_cache.
negate()
GHom Add::negate () const inline virtual
returns a negation of a selector homomorphism h, such that h.negate() (d) = d - h(d)
Reimplemented from _GHom.
References GHom::ccompose(), and parameters.
operator<()
bool _GHom::operator< (const _GHom & h) const inherited
Ordering between _GHom. It is the chronological ordering of creation.
References _GHom::creation_counter.
operator==()
bool Add::operator== (const _GHom & h) const inline virtual
Comparator.
Used in case of hash collision. Should be appropriately defined in derived classes, in particular in user defined homomorphisms.
Implements _GHom.
References parameters.
print()
void Add::print (std::ostream & os) const inline virtual
Implements _GHom.
References parameters.
skip_variable()
bool Add::skip_variable (int) const inline virtual
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
This is defined as a StrongHom with : phi(var,val) { if (skip_variable(var)) return GShom(var, val, this); else { real behavior } }
Reimplemented from _GHom.
References GHom::add(), _GHom::get_concret(), parameters, partition_cache, and _GHom::skip_variable().
Referenced by eval(), get_partition(), and has_image().
Member Data Documentation
creation_counter
size_t _GHom::creation_counter private inherited
Counter of objects created (see constructors).
This is used for the ordering between homomorphisms.
Referenced by _GHom::_GHom(), and _GHom::operator<().
have_id
bool Add::have_id
immediat
bool _GHom::immediat mutable private inherited
For operation cache management.
If immediat==true, eval is called without attempting a cache hit. Currently only the constant homomorphism has this attribute set to true.
Referenced by GHom::operator()().
marking
bool _GHom::marking mutable private inherited
For garbage collection.
Used in the two phase garbage collection process. A Hom that is not marked after the first pass over the unicity table, will be sweeped in the second phase. Outside of garbage collection routine, marking should always bear the value false.
Referenced by GHom::garbage(), and GHom::mark().
parameters
param_t Add::parameters
Referenced by Add(), eval(), get_have_id(), get_parameters(), get_range(), has_image(), hash(), invert(), is_selector(), mark(), negate(), operator==(), print(), and skip_variable().
partition_cache
partition_cache_type Add::partition_cache mutable
Referenced by eval(), get_partition(), has_image(), mark(), and skip_variable().
refCounter
int _GHom::refCounter mutable private inherited
For garbage collection.
Counts the number of times a _GShom is referenced from the context of an Shom.
Referenced by Hom::Hom(), Hom::Hom(), Hom::Hom(), Hom::Hom(), Hom::operator=(), Hom::operator=(), GHom::refCounter(), and Hom::~Hom().
The documentation for this class was generated from the following file:
Hom.cpp
Please comment this page and report errors about it on the RefDocComments page.