DDD: nsMLShom::LeftConcat Class Reference
nsMLShom::LeftConcat Class Reference
Public Member Functions
LeftConcat (const GSDD &l, const MLShom &_h, int ref=0)
bool operator== (const _MLShom &other) const
_MLShom * clone () const
size_t hash () const
unique table trivia
bool skip_variable (int) const
SHomNodeMap eval (const GSDD &d) const
virtual bool shouldCache () const
test if caching should be done : default means should cache
Private Member Functions
virtual void mark () const
For garbage collection. Used in first phase of garbage collection.
Private Attributes
GSDD left
MLShom h
int refCounter
For garbage collection.
bool marking
For garbage collection.
Constructor & Destructor Documentation
LeftConcat()
nsMLShom::LeftConcat::LeftConcat (const GSDD & l, const MLShom & _h, int ref = 0) inline
Member Function Documentation
clone()
_MLShom * nsMLShom::LeftConcat::clone () const inline virtual
Implements _MLShom.
eval()
SHomNodeMap nsMLShom::LeftConcat::eval (const GSDD & d) const inline virtual
Implements _MLShom.
References AdditiveMap< K, V, EqualKey >::add(), AdditiveMap< K, V, EqualKey >::begin(), AdditiveMap< K, V, EqualKey >::end(), h, and left.
hash()
size_t nsMLShom::LeftConcat::hash () const inline virtual
unique table trivia
Implements _MLShom.
References h, MLShom::hash(), GSDD::hash(), and left.
mark()
virtual void _MLShom::mark () const inline private virtual inherited
For garbage collection. Used in first phase of garbage collection.
operator==()
bool nsMLShom::LeftConcat::operator== (const _MLShom & other) const inline virtual
Implements _MLShom.
References h, and left.
shouldCache()
virtual bool _MLShom::shouldCache () const inline virtual inherited
test if caching should be done : default means should cache
Reimplemented in nsMLShom::Identity.
skip_variable()
bool nsMLShom::LeftConcat::skip_variable (int) const inline
Member Data Documentation
h
MLShom nsMLShom::LeftConcat::h private
Referenced by eval(), hash(), and operator==().
left
GSDD nsMLShom::LeftConcat::left private
Referenced by eval(), hash(), and operator==().
marking
bool _MLShom::marking mutable private inherited
For garbage collection.
Used in the two phase garbage collection process. A Shom that is not marked after the first pass over the unicity table, will be sweeped in the second phase. Outside of garbage collection routine, marking should always bear the value false.
Referenced by MLShom::garbage().
refCounter
int _MLShom::refCounter mutable private inherited
For garbage collection.
Counts the number of times a _MLHom is referenced from the context of an MLHom.
The documentation for this class was generated from the following file:
MLSHom.cpp
Please comment this page and report errors about it on the RefDocComments page.