DDD: nsMLHom::ConstantUp Class Reference
nsMLHom::ConstantUp Class Reference
Public Member Functions
ConstantUp (const GHom &uup, const MLHom &ddown)
bool operator== (const _MLHom &other) const
_MLHom * clone () const
size_t hash () const
unique table trivia
bool skip_variable (int) const
HomNodeMap eval (const GDDD &d) const
virtual bool shouldCache () const
test if caching should be done : default means should cache
Private Member Functions
virtual void mark () const
For garbage collection. Used in first phase of garbage collection.
Private Attributes
GHom up
MLHom down
int refCounter
For garbage collection.
bool marking
For garbage collection.
Constructor & Destructor Documentation
ConstantUp()
nsMLHom::ConstantUp::ConstantUp (const GHom & uup, const MLHom & ddown) inline
Member Function Documentation
clone()
_MLHom * nsMLHom::ConstantUp::clone () const inline virtual
Implements _MLHom.
eval()
HomNodeMap nsMLHom::ConstantUp::eval (const GDDD & d) const inline virtual
Implements _MLHom.
References AdditiveMap< K, V, EqualKey >::add(), AdditiveMap< K, V, EqualKey >::begin(), GHom::compose(), down, AdditiveMap< K, V, EqualKey >::end(), and up.
hash()
size_t nsMLHom::ConstantUp::hash () const inline virtual
unique table trivia
Implements _MLHom.
References down, GHom::hash(), MLHom::hash(), and up.
mark()
virtual void _MLHom::mark () const inline private virtual inherited
For garbage collection. Used in first phase of garbage collection.
operator==()
bool nsMLHom::ConstantUp::operator== (const _MLHom & other) const inline virtual
Implements _MLHom.
References down, and up.
shouldCache()
virtual bool _MLHom::shouldCache () const inline virtual inherited
test if caching should be done : default means should cache
Reimplemented in nsMLHom::Identity.
skip_variable()
bool nsMLHom::ConstantUp::skip_variable (int) const inline
Member Data Documentation
down
MLHom nsMLHom::ConstantUp::down private
Referenced by eval(), hash(), and operator==().
marking
bool _MLHom::marking mutable private inherited
For garbage collection.
Used in the two phase garbage collection process. A Shom that is not marked after the first pass over the unicity table, will be sweeped in the second phase. Outside of garbage collection routine, marking should always bear the value false.
Referenced by MLHom::garbage().
refCounter
int _MLHom::refCounter mutable private inherited
For garbage collection.
Counts the number of times a _MLHom is referenced from the context of an MLHom.
up
GHom nsMLHom::ConstantUp::up private
Referenced by eval(), hash(), and operator==().
The documentation for this class was generated from the following file:
MLHom.cpp
Please comment this page and report errors about it on the RefDocComments page.