DDD: ext_hash_map< Key, Data, HashKey, EqualKey > Class Template Reference
ext_hash_map< Key, Data, HashKey, EqualKey > Class Template Reference
#include <util/ext_hash_map.hh>
Classes
class accessor
class const_accessor
Public Types
typedef google::sparse_hash_map< Key, Data, HashKey, EqualKey > internal_hash_map
typedef internal_hash_map::iterator iterator
typedef internal_hash_map::const_iterator const_iterator
typedef internal_hash_map::size_type size_type
Public Member Functions
ext_hash_map ()
ext_hash_map (size_t s)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
size_type size () const
bool empty () const
void clear ()
bool find (accessor &result, const Key &key)
bool find (const_accessor &result, const Key &key) const
bool insert (accessor &result, const Key &key)
bool erase (const Key &key)
Private Attributes
internal_hash_map map_
Friends
class const_accessor
class accessor
Member Typedef Documentation
const_iterator
template<typename Key , typename Data , typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> typedef internal_hash_map::const_iterator ext_hash_map< Key, Data, HashKey, EqualKey >::const_iterator
internal_hash_map
template<typename Key , typename Data , typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> typedef google::sparse_hash_map<Key,Data,HashKey,EqualKey> ext_hash_map< Key, Data, HashKey, EqualKey >::internal_hash_map
iterator
template<typename Key , typename Data , typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> typedef internal_hash_map::iterator ext_hash_map< Key, Data, HashKey, EqualKey >::iterator
size_type
template<typename Key , typename Data , typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> typedef internal_hash_map::size_type ext_hash_map< Key, Data, HashKey, EqualKey >::size_type
Constructor & Destructor Documentation
ext_hash_map() [1/2]
template<typename Key , typename Data , typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> ext_hash_map< Key, Data, HashKey, EqualKey >::ext_hash_map () inline
ext_hash_map() [2/2]
template<typename Key , typename Data , typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> ext_hash_map< Key, Data, HashKey, EqualKey >::ext_hash_map (size_t s) inline
Member Function Documentation
begin() [1/2]
template<typename Key , typename Data , typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> iterator ext_hash_map< Key, Data, HashKey, EqualKey >::begin () inline
References ext_hash_map< Key, Data, HashKey, EqualKey >::map_.
begin() [2/2]
template<typename Key , typename Data , typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> const_iterator ext_hash_map< Key, Data, HashKey, EqualKey >::begin () const inline
References ext_hash_map< Key, Data, HashKey, EqualKey >::map_.
clear()
template<typename Key , typename Data , typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> void ext_hash_map< Key, Data, HashKey, EqualKey >::clear () inline
References ext_hash_map< Key, Data, HashKey, EqualKey >::map_.
Referenced by MyNbStates::clear(), MySDDNbStates::clear(), Cache< FuncType, ParamType, ResType, EvalFunc >::clear(), and MLCache< MLHomType, NodeType, HomNodeMapType >::clear().
empty()
template<typename Key , typename Data , typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> bool ext_hash_map< Key, Data, HashKey, EqualKey >::empty () const inline
References ext_hash_map< Key, Data, HashKey, EqualKey >::map_.
end() [1/2]
template<typename Key , typename Data , typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> iterator ext_hash_map< Key, Data, HashKey, EqualKey >::end () inline
References ext_hash_map< Key, Data, HashKey, EqualKey >::map_.
end() [2/2]
template<typename Key , typename Data , typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> const_iterator ext_hash_map< Key, Data, HashKey, EqualKey >::end () const inline
References ext_hash_map< Key, Data, HashKey, EqualKey >::map_.
erase()
template<typename Key , typename Data , typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> bool ext_hash_map< Key, Data, HashKey, EqualKey >::erase (const Key & key) inline
References ext_hash_map< Key, Data, HashKey, EqualKey >::map_.
find() [1/2]
template<typename Key , typename Data , typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> bool ext_hash_map< Key, Data, HashKey, EqualKey >::find (accessor & result, const Key & key) inline
References ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::current_bucket_, ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::has_result_, and ext_hash_map< Key, Data, HashKey, EqualKey >::map_.
Referenced by Cache< FuncType, ParamType, ResType, EvalFunc >::insert(), MLCache< MLHomType, NodeType, HomNodeMapType >::insert(), MyNbStates::nbStates(), and MySDDNbStates::nbStates().
find() [2/2]
template<typename Key , typename Data , typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> bool ext_hash_map< Key, Data, HashKey, EqualKey >::find (const_accessor & result, const Key & key) const inline
References ext_hash_map< Key, Data, HashKey, EqualKey >::const_accessor::current_bucket_, ext_hash_map< Key, Data, HashKey, EqualKey >::const_accessor::has_result_, and ext_hash_map< Key, Data, HashKey, EqualKey >::map_.
insert()
template<typename Key , typename Data , typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> bool ext_hash_map< Key, Data, HashKey, EqualKey >::insert (accessor & result, const Key & key) inline
References ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::current_bucket_, ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::has_result_, and ext_hash_map< Key, Data, HashKey, EqualKey >::map_.
Referenced by Cache< FuncType, ParamType, ResType, EvalFunc >::insert(), MLCache< MLHomType, NodeType, HomNodeMapType >::insert(), MyNbStates::nbStates(), and MySDDNbStates::nbStates().
size()
template<typename Key , typename Data , typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> size_type ext_hash_map< Key, Data, HashKey, EqualKey >::size () const inline
References ext_hash_map< Key, Data, HashKey, EqualKey >::map_.
Referenced by Cache< FuncType, ParamType, ResType, EvalFunc >::size(), and MLCache< MLHomType, NodeType, HomNodeMapType >::size().
Friends And Related Symbol Documentation
accessor
template<typename Key , typename Data , typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> friend class accessor friend
const_accessor
template<typename Key , typename Data , typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> friend class const_accessor friend
Member Data Documentation
map_
template<typename Key , typename Data , typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> internal_hash_map ext_hash_map< Key, Data, HashKey, EqualKey >::map_ private
Referenced by ext_hash_map< Key, Data, HashKey, EqualKey >::begin(), ext_hash_map< Key, Data, HashKey, EqualKey >::begin(), ext_hash_map< Key, Data, HashKey, EqualKey >::clear(), ext_hash_map< Key, Data, HashKey, EqualKey >::empty(), ext_hash_map< Key, Data, HashKey, EqualKey >::end(), ext_hash_map< Key, Data, HashKey, EqualKey >::end(), ext_hash_map< Key, Data, HashKey, EqualKey >::erase(), ext_hash_map< Key, Data, HashKey, EqualKey >::find(), ext_hash_map< Key, Data, HashKey, EqualKey >::find(), ext_hash_map< Key, Data, HashKey, EqualKey >::insert(), and ext_hash_map< Key, Data, HashKey, EqualKey >::size().
The documentation for this class was generated from the following file:
util/ext_hash_map.hh
Please comment this page and report errors about it on the RefDocComments page.