DDD: fobs::FixObserver Class Reference
fobs::FixObserver Class Reference abstract
#include <FixObserver.hh>
Public Member Functions
FixObserver ()
virtual ~FixObserver ()
virtual bool should_interrupt (const GSDD &after, const GSDD &before)=0
virtual bool should_interrupt (const GDDD &after, const GDDD &before)=0
virtual bool was_interrupted () const =0
virtual void update (const GSDD &after, const GSDD &before)=0
virtual void update (const GDDD &after, const GDDD &before)=0
Constructor & Destructor Documentation
FixObserver()
fobs::FixObserver::FixObserver () inline
~FixObserver()
virtual fobs::FixObserver::~FixObserver () inline virtual
Member Function Documentation
should_interrupt() [1/2]
virtual bool fobs::FixObserver::should_interrupt (const GDDD & after, const GDDD & before) pure virtual
Implemented in fobs::DefaultObserver.
should_interrupt() [2/2]
virtual bool fobs::FixObserver::should_interrupt (const GSDD & after, const GSDD & before) pure virtual
Warning
: if should_interrult() returns true, then it MUST return true at least until the next call to update(). The attribute is_interrupted is here for this purpose: it can be set to true only by should_interrupt and to false only by update, and is_interrupted => should_interrupt returns true
Implemented in fobs::DefaultObserver.
Referenced by testWasInterrupt().
update() [1/2]
virtual void fobs::FixObserver::update (const GDDD & after, const GDDD & before) pure virtual
Implemented in fobs::DefaultObserver.
update() [2/2]
virtual void fobs::FixObserver::update (const GSDD & after, const GSDD & before) pure virtual
Implemented in fobs::DefaultObserver.
Referenced by sns::Fixpoint::eval(), sns::testShouldInterrupt(), and testWasInterrupt().
was_interrupted()
virtual bool fobs::FixObserver::was_interrupted () const pure virtual
Implemented in fobs::DefaultObserver.
Referenced by sns::Fixpoint::eval().
The documentation for this class was generated from the following file:
FixObserver.hh
Please comment this page and report errors about it on the RefDocComments page.