DDD: sns::MLShomAdapter Class Reference
sns::MLShomAdapter Class Reference
Public Member Functions
MLShomAdapter (const MLShom &hh)
bool operator== (const _GShom &other) const
Comparator.
size_t hash () const
Hash key computation.
_GShom * clone () const
GSDD eval (const GSDD &d) const
The computation function responsible for evaluation over a node.
void mark () const
For garbage collection. Used in first phase of garbage collection.
void print (std::ostream &os) const
GSDD has_image_skip (const GSDD &) const
virtual bool skip_variable (int) const
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
virtual bool is_selector () const
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
virtual const GShom::range_t get_range () const
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
virtual GSDD has_image (const GSDD &d) const
virtual GShom compose (const GShom &) const
void mark_if_refd () const
void ref () const
void deref () const
unsigned long int refCounter () const
bool is_marked () const
void set_mark (bool val) const
virtual GShom invert (const GSDD &) const
Static Public Member Functions
static const _GShom * get_concret (const GShom &gshom)
TODO : this is a dirty trick to allow us to do terms rewriting in Add, Fixpoint etc... A more elegant architecture would be nice.
Private Member Functions
GSDD eval_skip (const GSDD &) const
The procedure responsible for propagating efficiently across "skipped" variable nodes.
virtual bool immediat () const
For operation cache management.
Private Attributes
MLShom h
int _refCounter
For garbage collection.
Constructor & Destructor Documentation
MLShomAdapter()
sns::MLShomAdapter::MLShomAdapter (const MLShom & hh) inline
Member Function Documentation
clone()
_GShom * sns::MLShomAdapter::clone () const inline virtual
Implements _GShom.
compose()
GShom _GShom::compose (const GShom & r) const virtual inherited
References GShom::id, and GSDD::null.
Referenced by GShom::compose().
deref()
void _GShom::deref () const inline inherited
References _GShom::_refCounter.
Referenced by Shom::operator=(), Shom::operator=(), and Shom::~Shom().
eval()
GSDD sns::MLShomAdapter::eval (const GSDD &) const inline virtual
The computation function responsible for evaluation over a node.
Users should not directly use this. Normal behavior is to use GShom::operator() that encapsulates this call with operation caching.
Implements _GShom.
References SDED::add(), AdditiveMap< K, V, EqualKey >::begin(), AdditiveMap< K, V, EqualKey >::end(), and h.
eval_skip()
GSDD _GShom::eval_skip (const GSDD & d) const private inherited
The procedure responsible for propagating efficiently across "skipped" variable nodes.
References GSDD::begin(), GSDD::end(), _GShom::eval(), GShom::id, _GShom::immediat(), GSDD::nbsons(), GSDD::null, GSDD::one, _GShom::skip_variable(), square_union(), GSDD::top, and GSDD::variable().
Referenced by GShom::eval().
get_concret()
static const _GShom * _GShom::get_concret (const GShom & gshom) inline static inherited
TODO : this is a dirty trick to allow us to do terms rewriting in Add, Fixpoint etc... A more elegant architecture would be nice.
References GShom::concret.
Referenced by addCompositionParameter(), addParameter(), buildUnionParameters(), sns::RecFireSat::eval(), sns::Fixpoint::eval(), sns::Add::factorizeByLevel(), GShom::GShom(), sns::Fixpoint::has_image(), operator!(), operator*(), sns::recFireSat(), sns::Inter::skip_variable(), sns::Add::skip_variable(), and sns::RightConcat::skip_variable().
get_range()
virtual const GShom::range_t _GShom::get_range () const inline virtual inherited
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
Reimplemented in sns::LocalApply, sns::SLocalApply, sns::SNotCond, sns::And, sns::Add, sns::RecFireSat, sns::Compose, and sns::Fixpoint.
References GShom::full_range.
Referenced by GShom::get_range().
has_image()
GSDD _GShom::has_image (const GSDD & d) const virtual inherited
Reimplemented in sns::Identity, sns::Inter, sns::LocalApply, sns::SLocalApply, sns::SNotCond, sns::And, sns::Add, sns::Compose, sns::LeftConcat, sns::RightConcat, sns::Fixpoint, and StrongShom.
References _GShom::GShom.
Referenced by sns::Inter::has_image(), sns::SNotCond::has_image(), sns::Compose::has_image(), sns::Fixpoint::has_image(), and _GShom::has_image_skip().
has_image_skip()
GSDD _GShom::has_image_skip (const GSDD & d) const inherited
References GSDD::begin(), GSDD::end(), GShom::has_image(), _GShom::has_image(), GShom::id, GSDD::null, GSDD::one, _GShom::skip_variable(), GSDD::top, and GSDD::variable().
hash()
size_t sns::MLShomAdapter::hash () const inline virtual
Hash key computation.
It is essential for good hash table operation that the spread of the keys be as good as possible. Also, fast hash key computation is a good design goal. Note that bad hash functions will yield more collisions, thus equality comparisons which may be quite costly.
Implements _GShom.
References h, and MLShom::hash().
immediat()
virtual bool _GShom::immediat () const inline private virtual inherited
For operation cache management.
If immediat==true, eval is called without attempting a cache hit. Currently only the constant homomorphism has this attribute set to true. Overload and return true for immediate computations.
Reimplemented in sns::Identity, and sns::Constant.
Referenced by _GShom::eval_skip(), and GShom::operator()().
invert()
virtual GShom _GShom::invert (const GSDD &) const inline virtual inherited
Reimplemented in sns::Identity, sns::Constant, sns::SApply2k, sns::Mult, sns::Inter, sns::LocalApply, sns::SLocalApply, sns::And, sns::Add, sns::RecFireSat, sns::Compose, sns::Minus, sns::HomMinus, and sns::Fixpoint.
References _GShom::is_selector(), Shom::null, and _GShom::print().
Referenced by GShom::invert().
is_marked()
bool _GShom::is_marked () const inline inherited
References _GShom::_refCounter.
Referenced by _GShom::set_mark().
is_selector()
virtual bool _GShom::is_selector () const inline virtual inherited
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
Reimplemented in sns::Identity, sns::Constant, sns::SApply2k, sns::Mult, sns::Inter, sns::SDomExtract, sns::LocalApply, sns::SLocalApply, sns::SNotCond, sns::And, sns::Add, sns::RecFireSat, sns::Compose, sns::Minus, sns::HomMinus, and sns::Fixpoint.
Referenced by _GShom::invert(), and GShom::is_selector().
mark()
void sns::MLShomAdapter::mark () const inline virtual
For garbage collection. Used in first phase of garbage collection.
???????
Reimplemented from _GShom.
mark_if_refd()
void _GShom::mark_if_refd () const inline inherited
References _GShom::refCounter(), and _GShom::set_mark().
operator==()
bool sns::MLShomAdapter::operator== (const _GShom & h) const inline virtual
Comparator.
Used in case of hash collision. Should be appropriately defined in derived classes, in particular in user defined homomorphisms.
Implements _GShom.
References h.
print()
void sns::MLShomAdapter::print (std::ostream & os) const inline virtual
Implements _GShom.
ref()
void _GShom::ref () const inline inherited
References _GShom::_refCounter.
Referenced by Shom::operator=(), Shom::operator=(), Shom::Shom(), Shom::Shom(), Shom::Shom(), and Shom::Shom().
refCounter()
unsigned long int _GShom::refCounter () const inline inherited
References _GShom::_refCounter.
Referenced by _GShom::mark_if_refd(), Shom::operator=(), Shom::operator=(), GShom::refCounter(), and Shom::~Shom().
set_mark()
void _GShom::set_mark (bool val) const inline inherited
References _GShom::_refCounter, _GShom::is_marked(), and _GShom::mark().
Referenced by GShom::garbage(), GShom::mark(), and _GShom::mark_if_refd().
skip_variable()
virtual bool _GShom::skip_variable (int) const inline virtual inherited
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
This is defined as a StrongHom with : phi(var,val) { if (skip_variable(var)) return GShom(var, val, this); else { real behavior } }
Reimplemented in sns::SApply2k, sns::Inter, sns::LocalApply, sns::SLocalApply, sns::SNotCond, sns::And, sns::Add, sns::RecFireSat, sns::Compose, sns::RightConcat, sns::Fixpoint, sns::Identity, and sns::SDomExtract.
Referenced by _GShom::eval_skip(), _GShom::has_image_skip(), sns::Inter::skip_variable(), sns::Add::skip_variable(), sns::RightConcat::skip_variable(), and GShom::skip_variable().
Member Data Documentation
_refCounter
int _GShom::_refCounter mutable private inherited
For garbage collection.
Counts the number of times a _GShom is referenced from the context of an Shom. For garbage collection: lowest bit of refCounter gives marking value for mark&sweep. Used in the two phase garbage collection process. A Shom that is not marked after the first pass over the unicity table, will be sweeped in the second phase. Outside of garbage collection routine, marking should always bear the value false.
Referenced by _GShom::deref(), _GShom::is_marked(), _GShom::ref(), _GShom::refCounter(), and _GShom::set_mark().
h
MLShom sns::MLShomAdapter::h private
Referenced by eval(), hash(), and operator==().
The documentation for this class was generated from the following file:
SHom.cpp
Please comment this page and report errors about it on the RefDocComments page.