DDD: sns::Fixpoint Class Reference
sns::Fixpoint Class Reference
Public Member Functions
Fixpoint (const GShom &a, int ref=0, bool can_garbage=false)
bool operator== (const _GShom &h) const
Comparator.
size_t hash () const
Hash key computation.
_GShom * clone () const
bool skip_variable (int var) const
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
const GShom::range_t get_range () const
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
bool is_selector () const
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
GSDD has_image (const GSDD &d) const
GShom invert (const GSDD &pot) const
GSDD eval (const GSDD &d) const
The computation function responsible for evaluation over a node.
void mark () const
For garbage collection. Used in first phase of garbage collection.
void print (std::ostream &os) const
GSDD has_image_skip (const GSDD &) const
virtual GShom compose (const GShom &) const
void mark_if_refd () const
void ref () const
void deref () const
unsigned long int refCounter () const
bool is_marked () const
void set_mark (bool val) const
Static Public Member Functions
static const _GShom * get_concret (const GShom &gshom)
TODO : this is a dirty trick to allow us to do terms rewriting in Add, Fixpoint etc... A more elegant architecture would be nice.
Private Member Functions
GSDD eval_skip (const GSDD &) const
The procedure responsible for propagating efficiently across "skipped" variable nodes.
virtual bool immediat () const
For operation cache management.
Private Attributes
GShom arg
bool can_garbage
int _refCounter
For garbage collection.
Constructor & Destructor Documentation
Fixpoint()
sns::Fixpoint::Fixpoint (const GShom & a, int ref = 0, bool can_garbage = false) inline
Member Function Documentation
clone()
_GShom * sns::Fixpoint::clone () const inline virtual
Implements _GShom.
compose()
GShom _GShom::compose (const GShom & r) const virtual inherited
References GShom::id, and GSDD::null.
Referenced by GShom::compose().
deref()
void _GShom::deref () const inline inherited
References _GShom::_refCounter.
Referenced by Shom::operator=(), Shom::operator=(), and Shom::~Shom().
eval()
GSDD sns::Fixpoint::eval (const GSDD &) const inline virtual
The computation function responsible for evaluation over a node.
Users should not directly use this. Normal behavior is to use GShom::operator() that encapsulates this call with operation caching.
Step 1 : identify G = G_part + LF_part such that g \in LF_part <=> g = l & f
END RECFIREANDSAT CASE
Implements _GShom.
References GShom::add, arg, can_garbage, GShom::DFS, sns::Add::partition::F, fixpoint(), sns::Add::partition::G, MemoryManager::garbage(), _GShom::get_concret(), fobs::get_fixobserver(), GShom::getFixpointStrategy(), GShom::getSaturationStrategy(), _GShom::GShom, sns::Add::partition::has_local, GShom::id, sns::Add::partition::L, localApply(), GSDD::mark(), GShom::mark(), GSDD::null, GSDD::one, GShom::RECFIREANDSAT, sns::recFireSat(), _GShom::Shom, MemoryManager::should_garbage(), sns::testShouldInterrupt(), sns::testWasInterrupt(), GSDD::top, trace, fobs::FixObserver::update(), GSDD::variable(), and fobs::FixObserver::was_interrupted().
eval_skip()
GSDD _GShom::eval_skip (const GSDD & d) const private inherited
The procedure responsible for propagating efficiently across "skipped" variable nodes.
References GSDD::begin(), GSDD::end(), _GShom::eval(), GShom::id, _GShom::immediat(), GSDD::nbsons(), GSDD::null, GSDD::one, _GShom::skip_variable(), square_union(), GSDD::top, and GSDD::variable().
Referenced by GShom::eval().
get_concret()
static const _GShom * _GShom::get_concret (const GShom & gshom) inline static inherited
TODO : this is a dirty trick to allow us to do terms rewriting in Add, Fixpoint etc... A more elegant architecture would be nice.
References GShom::concret.
Referenced by addCompositionParameter(), addParameter(), buildUnionParameters(), sns::RecFireSat::eval(), eval(), sns::Add::factorizeByLevel(), GShom::GShom(), has_image(), operator!(), operator*(), sns::recFireSat(), sns::Inter::skip_variable(), sns::Add::skip_variable(), and sns::RightConcat::skip_variable().
get_range()
const GShom::range_t sns::Fixpoint::get_range () const inline virtual
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
Reimplemented from _GShom.
References arg, and GShom::get_range().
has_image()
GSDD sns::Fixpoint::has_image (const GSDD & d) const inline virtual
Reimplemented from _GShom.
References arg, can_garbage, sns::Add::partition::F, fixpoint(), _GShom::get_concret(), _GShom::GShom, GShom::has_image(), _GShom::has_image(), sns::Add::partition::has_local, GHom::id, GShom::id, sns::Add::partition::L, localApply(), GSDD::null, GSDD::one, GSDD::top, and GSDD::variable().
has_image_skip()
GSDD _GShom::has_image_skip (const GSDD & d) const inherited
References GSDD::begin(), GSDD::end(), GShom::has_image(), _GShom::has_image(), GShom::id, GSDD::null, GSDD::one, _GShom::skip_variable(), GSDD::top, and GSDD::variable().
hash()
size_t sns::Fixpoint::hash () const inline virtual
Hash key computation.
It is essential for good hash table operation that the spread of the keys be as good as possible. Also, fast hash key computation is a good design goal. Note that bad hash functions will yield more collisions, thus equality comparisons which may be quite costly.
Implements _GShom.
References arg, and GShom::hash().
immediat()
virtual bool _GShom::immediat () const inline private virtual inherited
For operation cache management.
If immediat==true, eval is called without attempting a cache hit. Currently only the constant homomorphism has this attribute set to true. Overload and return true for immediate computations.
Reimplemented in sns::Identity, and sns::Constant.
Referenced by _GShom::eval_skip(), and GShom::operator()().
invert()
GShom sns::Fixpoint::invert (const GSDD & pot) const inline virtual
Reimplemented from _GShom.
References arg, fixpoint(), GShom::id, and GShom::invert().
is_marked()
bool _GShom::is_marked () const inline inherited
References _GShom::_refCounter.
Referenced by _GShom::set_mark().
is_selector()
bool sns::Fixpoint::is_selector () const inline virtual
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
Reimplemented from _GShom.
References arg, and GShom::is_selector().
mark()
void sns::Fixpoint::mark () const inline virtual
For garbage collection. Used in first phase of garbage collection.
Reimplemented from _GShom.
References arg, and GShom::mark().
mark_if_refd()
void _GShom::mark_if_refd () const inline inherited
References _GShom::refCounter(), and _GShom::set_mark().
operator==()
bool sns::Fixpoint::operator== (const _GShom & h) const inline virtual
Comparator.
Used in case of hash collision. Should be appropriately defined in derived classes, in particular in user defined homomorphisms.
Implements _GShom.
References arg.
print()
void sns::Fixpoint::print (std::ostream & os) const inline virtual
Implements _GShom.
References arg.
ref()
void _GShom::ref () const inline inherited
References _GShom::_refCounter.
Referenced by Shom::operator=(), Shom::operator=(), Shom::Shom(), Shom::Shom(), Shom::Shom(), and Shom::Shom().
refCounter()
unsigned long int _GShom::refCounter () const inline inherited
References _GShom::_refCounter.
Referenced by _GShom::mark_if_refd(), Shom::operator=(), Shom::operator=(), GShom::refCounter(), and Shom::~Shom().
set_mark()
void _GShom::set_mark (bool val) const inline inherited
References _GShom::_refCounter, _GShom::is_marked(), and _GShom::mark().
Referenced by GShom::garbage(), GShom::mark(), and _GShom::mark_if_refd().
skip_variable()
bool sns::Fixpoint::skip_variable (int) const inline virtual
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
This is defined as a StrongHom with : phi(var,val) { if (skip_variable(var)) return GShom(var, val, this); else { real behavior } }
Reimplemented from _GShom.
References arg, and GShom::skip_variable().
Member Data Documentation
_refCounter
int _GShom::_refCounter mutable private inherited
For garbage collection.
Counts the number of times a _GShom is referenced from the context of an Shom. For garbage collection: lowest bit of refCounter gives marking value for mark&sweep. Used in the two phase garbage collection process. A Shom that is not marked after the first pass over the unicity table, will be sweeped in the second phase. Outside of garbage collection routine, marking should always bear the value false.
Referenced by _GShom::deref(), _GShom::is_marked(), _GShom::ref(), _GShom::refCounter(), and _GShom::set_mark().
arg
GShom sns::Fixpoint::arg private
Referenced by eval(), get_range(), has_image(), hash(), invert(), is_selector(), mark(), operator==(), print(), and skip_variable().
can_garbage
bool sns::Fixpoint::can_garbage private
Referenced by eval(), and has_image().
The documentation for this class was generated from the following file:
SHom.cpp
Please comment this page and report errors about it on the RefDocComments page.