DDD: DDD.h File Reference
DDD.h File Reference
#include <iosfwd>
#include <string>
#include <vector>
#include "ddd/DataSet.h"
#include "ddd/hashfunc.hh"
Classes
class GDDD
This class is the base class representing a Data Decision Diagram.
class DDD
This class is the public interface for manipulating Data Decision Diagrams.
struct std::less< GDDD >
Compares two DDD in hash tables.
Namespaces
namespace std
Functions
std::ostream & operator<< (std::ostream &, const GDDD &)
Textual output of DDD into a stream in (relatively) human readable format.
GDDD operator^ (const GDDD &, const GDDD &)
Operator for concatenation of DDD.
GDDD operator+ (const GDDD &, const GDDD &)
Operator for union of DDD.
GDDD operator* (const GDDD &, const GDDD &)
Operator for intersection of DDD.
GDDD operator- (const GDDD &, const GDDD &)
Operator for set difference of DDD.
Function Documentation
operator*()
GDDD operator* (const GDDD & g1, const GDDD & g2)
Operator for intersection of DDD.
Semantics : d1 * d2 designates the intersection of the two sets
References _DED_Mult::create().
operator+()
GDDD operator+ (const GDDD & g1, const GDDD & g2)
Operator for union of DDD.
Semantics : d1 + d2 produces the union d1 and d2
References DED::add().
operator-()
GDDD operator- (const GDDD & g1, const GDDD & g2)
Operator for set difference of DDD.
Semantics : d1 - d2 contains elements in d1 and not in d2
References _DED_Minus::create().
operator<<()
std::ostream & operator<< (std::ostream & os, const GDDD & g)
Textual output of DDD into a stream in (relatively) human readable format.
A textual output.
Don't use it with large number of paths as each element is printed on a different line
operator^()
GDDD operator^ (const GDDD & g1, const GDDD & g2)
Operator for concatenation of DDD.
Semantics : d1 ^ d2 replaces "one" terminals of d1 by d2
References _DED_Concat::create().
Please comment this page and report errors about it on the RefDocComments page.