DDD: DED.cpp File Reference
DED.cpp File Reference
#include <set>
#include <iostream>
#include <map>
#include <cassert>
#include <typeinfo>
#include "ddd/util/configuration.hh"
#include "ddd/util/set.hh"
#include "ddd/DDD.h"
#include "ddd/DED.h"
#include "ddd/Hom.h"
#include "ddd/UniqueTable.h"
Classes
class _DED
class _DED_Add
class _DED_Mult
class _DED_Minus
class _DED_Concat
class _DED_Hom
Namespaces
namespace DED
Typedefs
typedef UniqueTable< _DED > DEDtable
Functions
static GDDD compute (const _DED &op)
size_t DED::peak ()
void DED::garbage ()
GDDD DED::add (const std::set< GDDD > &s)
GDDD operator+ (const GDDD &g1, const GDDD &g2)
Operator for union of DDD.
GDDD operator* (const GDDD &g1, const GDDD &g2)
Operator for intersection of DDD.
GDDD operator^ (const GDDD &g1, const GDDD &g2)
Operator for concatenation of DDD.
GDDD operator- (const GDDD &g1, const GDDD &g2)
Operator for set difference of DDD.
Variables
static DEDtable uniqueDED
static int Hits =0
static int Misses =0
static size_t DEDpeak = 0
Typedef Documentation
DEDtable
typedef UniqueTable<_DED> DEDtable
Function Documentation
compute()
static GDDD compute (const _DED & op) static
References uniqueDED.
Referenced by _DED_Mult::create(), _DED_Minus::create(), _DED_Concat::create(), _DED_Hom::create(), and _DED_Add::create().
operator*()
GDDD operator* (const GDDD & g1, const GDDD & g2)
Operator for intersection of DDD.
Semantics : d1 * d2 designates the intersection of the two sets
References _DED_Mult::create().
operator+()
GDDD operator+ (const GDDD & g1, const GDDD & g2)
Operator for union of DDD.
Semantics : d1 + d2 produces the union d1 and d2
References DED::add().
operator-()
GDDD operator- (const GDDD & g1, const GDDD & g2)
Operator for set difference of DDD.
Semantics : d1 - d2 contains elements in d1 and not in d2
References _DED_Minus::create().
operator^()
GDDD operator^ (const GDDD & g1, const GDDD & g2)
Operator for concatenation of DDD.
Semantics : d1 ^ d2 replaces "one" terminals of d1 by d2
References _DED_Concat::create().
Variable Documentation
DEDpeak
size_t DEDpeak = 0 static
Referenced by DED::garbage(), and DED::peak().
Hits
int Hits =0 static
Referenced by DED::pstats().
Misses
int Misses =0 static
Referenced by DED::pstats().
uniqueDED
DEDtable uniqueDED static
Referenced by compute(), DED::garbage(), DED::peak(), DED::pstats(), and DED::statistics().
Please comment this page and report errors about it on the RefDocComments page.