DDD: util/dotExporter.cpp File Reference
dotExporter.cpp File Reference
#include "ddd/util/dotExporter.h"
#include <typeinfo>
#include <map>
#include <iostream>
#include <sstream>
#include <fstream>
#include "ddd/util/hash_support.hh"
#include "ddd/util/hash_set.hh"
Classes
class dotExporter
class hDotExporter
Functions
int exportDot (const GSDD &g, const string &path, bool hierarchical, bool multiT)
static void addSDD (const GSDD &d)
void exportUniqueTable (const GSDD &d, const std::string &path)
Variables
static dotHighlight dotH = dotHighlight("table")
Function Documentation
addSDD()
static void addSDD (const GSDD & d) static
References dotHighlight::addSDD(), and dotH.
Referenced by exportUniqueTable().
exportDot()
int exportDot (const GSDD & g, const string & path, bool hierarchical, bool multiT)
References dotExporter::init().
exportUniqueTable()
void exportUniqueTable (const GSDD & d, const std::string & path)
References addSDD(), dotH, dotHighlight::exportDot(), SDDutil::foreachTable(), dotHighlight::initialize(), and dotHighlight::setColor().
Variable Documentation
dotH
dotHighlight dotH = dotHighlight("table") static
Referenced by addSDD(), and exportUniqueTable().
Please comment this page and report errors about it on the RefDocComments page.