DDD: Hom_Basic.hh File Reference
Hom_Basic.hh File Reference
#include "ddd/DDD.h"
#include "ddd/Hom.h"
#include "ddd/SDD.h"
#include "ddd/SHom.h"
#include <functional>
Typedefs
typedef std::vector< DDD::val_t > state_t
an explicit representation of a state
typedef std::function< void(state_t &)> callback_t
A visitor callback function.
Functions
GHom varEqState (int var, int val)
GHom varNeqState (int var, int val)
GHom varGtState (int var, int val)
GHom varLtState (int var, int val)
GHom varLeqState (int var, int val)
GHom varGeqState (int var, int val)
GHom setVarConst (int var, int val)
GHom incVar (int var, int val)
GHom varEqVar (int var, int var2)
GHom varNeqVar (int var, int var2)
GHom varGtVar (int var, int var2)
GHom varLtVar (int var, int var2)
GHom varLeqVar (int var, int var2)
GHom varGeqVar (int var, int var2)
void iterate (const GDDD &node, callback_t *cb)
Explicit conversion : visit every path in the DDD (variable ids are removed)
void iterate (const GSDD &node, callback_t *cb)
Explicit conversion : visit every path in the DDD (variable ids are removed)
Typedef Documentation
callback_t
typedef std::function<void(state_t &)> callback_t
A visitor callback function.
state_t
typedef std::vector<DDD::val_t> state_t
an explicit representation of a state
Function Documentation
incVar()
GHom incVar (int var, int val)
Referenced by _incVar::invert().
iterate() [1/2]
void iterate (const GDDD & node, callback_t * cb)
Explicit conversion : visit every path in the DDD (variable ids are removed)
References iterateDDD().
iterate() [2/2]
void iterate (const GSDD & node, callback_t * cb)
Explicit conversion : visit every path in the DDD (variable ids are removed)
References iterateSDD().
setVarConst()
GHom setVarConst (int var, int val)
Referenced by _setVarConst::invert().
varEqState()
GHom varEqState (int var, int val)
References EQ, and varCompState().
Referenced by _setVarConst::invert().
varEqVar()
GHom varEqVar (int var, int var2)
References EQ, GHom::id, and varCompVar().
varGeqState()
GHom varGeqState (int var, int val)
References GEQ, and varCompState().
Referenced by _incVar::invert().
varGeqVar()
GHom varGeqVar (int var, int var2)
References GEQ, GHom::id, and varCompVar().
varGtState()
GHom varGtState (int var, int val)
References GT, and varCompState().
varGtVar()
GHom varGtVar (int var, int var2)
References GT, GDDD::null, and varCompVar().
varLeqState()
GHom varLeqState (int var, int val)
References LEQ, and varCompState().
Referenced by _incVar::invert().
varLeqVar()
GHom varLeqVar (int var, int var2)
References GHom::id, LEQ, and varCompVar().
varLtState()
GHom varLtState (int var, int val)
References LT, and varCompState().
varLtVar()
GHom varLtVar (int var, int var2)
References LT, GDDD::null, and varCompVar().
varNeqState()
GHom varNeqState (int var, int val)
References NEQ, and varCompState().
varNeqVar()
GHom varNeqVar (int var, int var2)
References NEQ, GDDD::null, and varCompVar().
Please comment this page and report errors about it on the RefDocComments page.