DDD: Hom_Basic.cpp File Reference
Hom_Basic.cpp File Reference
#include "ddd/Hom_Basic.hh"
Classes
class _VarCompState
class _setVarConst
class _incVar
class _VarCompVar
Typedefs
typedef enum comparator comparator
Enumerations
enum comparator {
EQ , NEQ , LT , GT ,
LEQ , GEQ
}
Functions
std::string to_string (comparator comp)
static comparator negateComp (comparator comp)
GHom varCompState (int var, comparator c, int val)
GHom varEqState (int var, int val)
GHom varNeqState (int var, int val)
GHom varGtState (int var, int val)
GHom varLeqState (int var, int val)
GHom varLtState (int var, int val)
GHom varGeqState (int var, int val)
GHom setVarConst (int var, int val)
GHom incVar (int var, int val)
static comparator invertComp (comparator comp)
GHom varCompVar (int var, comparator c, int var2)
GHom varEqVar (int var, int var2)
GHom varNeqVar (int var, int var2)
GHom varGeqVar (int var, int var2)
GHom varGtVar (int var, int var2)
GHom varLeqVar (int var, int var2)
GHom varLtVar (int var, int var2)
void iterateDDD (const GDDD &node, callback_t *cb, std::vector< DDD::val_t > &prefix)
void iterateSDD (const GSDD &node, callback_t *cb, std::vector< GDDD::val_t > &prefix)
void iterate (const GDDD &node, callback_t *cb)
Explicit conversion : visit every path in the DDD (variable ids are removed)
void iterate (const GSDD &node, callback_t *cb)
Explicit conversion : visit every path in the DDD (variable ids are removed)
Typedef Documentation
comparator
typedef enum comparator comparator
Enumeration Type Documentation
comparator
enum comparator
Enumerator
EQ
NEQ
LT
GT
LEQ
GEQ
Function Documentation
incVar()
GHom incVar (int var, int val)
Referenced by _incVar::invert().
invertComp()
static comparator invertComp (comparator comp) static
References EQ, GEQ, GT, LEQ, LT, and NEQ.
Referenced by _VarCompVar::phi().
iterate() [1/2]
void iterate (const GDDD & node, callback_t * cb)
Explicit conversion : visit every path in the DDD (variable ids are removed)
References iterateDDD().
iterate() [2/2]
void iterate (const GSDD & node, callback_t * cb)
Explicit conversion : visit every path in the DDD (variable ids are removed)
References iterateSDD().
iterateDDD()
void iterateDDD (const GDDD & node, callback_t * cb, std::vector< DDD::val_t > & prefix)
References iterateDDD(), GDDD::null, GDDD::one, and GDDD::top.
Referenced by iterate(), iterateDDD(), and iterateSDD().
iterateSDD()
void iterateSDD (const GSDD & node, callback_t * cb, std::vector< GDDD::val_t > & prefix)
References iterateDDD(), iterateSDD(), GSDD::null, GSDD::one, and GSDD::top.
Referenced by iterate(), and iterateSDD().
negateComp()
static comparator negateComp (comparator comp) static
References EQ, GEQ, GT, LEQ, LT, and NEQ.
Referenced by _VarCompState::negate().
setVarConst()
GHom setVarConst (int var, int val)
Referenced by _setVarConst::invert().
to_string()
std::string to_string (comparator comp)
References EQ, GEQ, GT, LEQ, LT, and NEQ.
Referenced by _VarCompState::print(), and _VarCompVar::print().
varCompState()
GHom varCompState (int var, comparator c, int val)
Referenced by _VarCompVar::phi(), varEqState(), varGeqState(), varGtState(), varLeqState(), varLtState(), and varNeqState().
varCompVar()
GHom varCompVar (int var, comparator c, int var2)
Referenced by varEqVar(), varGeqVar(), varGtVar(), varLeqVar(), varLtVar(), and varNeqVar().
varEqState()
GHom varEqState (int var, int val)
References EQ, and varCompState().
Referenced by _setVarConst::invert().
varEqVar()
GHom varEqVar (int var, int var2)
References EQ, GHom::id, and varCompVar().
varGeqState()
GHom varGeqState (int var, int val)
References GEQ, and varCompState().
Referenced by _incVar::invert().
varGeqVar()
GHom varGeqVar (int var, int var2)
References GEQ, GHom::id, and varCompVar().
varGtState()
GHom varGtState (int var, int val)
References GT, and varCompState().
varGtVar()
GHom varGtVar (int var, int var2)
References GT, GDDD::null, and varCompVar().
varLeqState()
GHom varLeqState (int var, int val)
References LEQ, and varCompState().
Referenced by _incVar::invert().
varLeqVar()
GHom varLeqVar (int var, int var2)
References GHom::id, LEQ, and varCompVar().
varLtState()
GHom varLtState (int var, int val)
References LT, and varCompState().
varLtVar()
GHom varLtVar (int var, int var2)
References LT, GDDD::null, and varCompVar().
varNeqState()
GHom varNeqState (int var, int val)
References NEQ, and varCompState().
varNeqVar()
GHom varNeqVar (int var, int var2)
References NEQ, GDDD::null, and varCompVar().
Please comment this page and report errors about it on the RefDocComments page.