DDD: sns Namespace Reference
sns Namespace Reference
Classes
class Add
class And
A commutative composition of n homomorphisms.
class Compose
class Constant
class Fixpoint
class HomMinus
class Identity
class Inter
class LeftConcat
class LocalApply
class Minus
class MLShomAdapter
class Mult
class RecFireSat
class RightConcat
class SApply2k
class SDomExtract
Extractor of variable domains for invert computations.
class SLocalApply
class SNotCond
Functions
const _GShom * getIdentity ()
bool testWasInterrupt (bool can_garbage, const GSDD &d1, const GSDD &d2)
bool testShouldInterrupt (bool can_garbage, const GSDD &d1, const GSDD &d2)
GShom recFireSat (const GShom &sat, const GShom &lf)
Variables
UniqueTable< _GShom > canonical
static ShomCache cache
static ImgShomCache imgcache
Function Documentation
getIdentity()
const _GShom * sns::getIdentity ()
References canonical.
recFireSat()
GShom sns::recFireSat (const GShom & sat, const GShom & lf)
References _GShom::get_concret().
Referenced by sns::RecFireSat::eval(), and sns::Fixpoint::eval().
testShouldInterrupt()
bool sns::testShouldInterrupt (bool can_garbage, const GSDD & d1, const GSDD & d2)
References fobs::get_fixobserver(), and fobs::FixObserver::update().
Referenced by sns::Fixpoint::eval().
testWasInterrupt()
bool sns::testWasInterrupt (bool can_garbage, const GSDD & d1, const GSDD & d2)
References fobs::get_fixobserver().
Referenced by sns::Fixpoint::eval().
Variable Documentation
cache
ShomCache sns::cache static
Referenced by GShom::cache_peak(), GShom::cache_size(), GShom::garbage(), GShom::operator()(), and GShom::pstats().
canonical
UniqueTable< _GShom > sns::canonical
Referenced by getIdentity().
imgcache
ImgShomCache sns::imgcache static
Referenced by GShom::garbage(), and GShom::has_image().
Please comment this page and report errors about it on the RefDocComments page.