DDD: process Namespace Reference
process Namespace Reference
Functions
double getTotalTime ()
unsigned long MemoryUsed (void)
size_t getResidentMemory ()
in Bytes
Function Documentation
getResidentMemory()
size_t process::getResidentMemory ()
in Bytes
References MemoryUsed().
Referenced by Statistic::load(), Statistic::load(), and MemoryManager::should_garbage().
getTotalTime()
double process::getTotalTime ()
Referenced by Statistic::load(), and Statistic::load().
MemoryUsed()
unsigned long process::MemoryUsed (void)
Referenced by getResidentMemory().
Please comment this page and report errors about it on the RefDocComments page.