DDD: SDED Namespace Reference
SDED Namespace Reference
Functions
GSDD add (const d3::set< GSDD >::type &)
unsigned int statistics ()
void pstats (bool reinit=true)
size_t peak ()
void garbage ()
Function Documentation
add()
GSDD SDED::add (const d3::set< GSDD >::type & s)
References _SDED_Add::create(), and GSDD::null.
Referenced by StrongShom::eval(), sns::SApply2k::eval(), sns::SDomExtract::eval(), sns::LocalApply::eval(), sns::SLocalApply::eval(), sns::Add::eval(), sns::RecFireSat::eval(), and sns::MLShomAdapter::eval().
garbage()
void SDED::garbage ()
References namespace_SDED::Max_SDED, UniqueTable< T >::size(), UniqueTable< T >::table, and uniqueSDED.
Referenced by MemoryManager::garbage().
peak()
size_t SDED::peak ()
References namespace_SDED::Max_SDED, UniqueTable< T >::size(), and uniqueSDED.
Referenced by Statistic::load().
pstats()
void SDED::pstats (bool reinit = true)
References namespace_SDED::Hits, namespace_SDED::Max_SDED, and namespace_SDED::Misses.
Referenced by MemoryManager::pstats().
statistics()
unsigned int SDED::statistics ()
References UniqueTable< T >::size(), and uniqueSDED.
Referenced by Statistic::load(), and MemoryManager::nbSDED().
Please comment this page and report errors about it on the RefDocComments page.