DDD: fobs Namespace Reference
fobs Namespace Reference
Classes
class DefaultObserver
class FixObserver
Functions
void set_fixobserver (FixObserver *o)
FixObserver * get_fixobserver ()
Variables
static FixObserver * obs = NULL
Function Documentation
get_fixobserver()
FixObserver * fobs::get_fixobserver ()
References obs.
Referenced by Fixpoint::eval(), sns::Fixpoint::eval(), sns::testShouldInterrupt(), testWasInterrupt(), and sns::testWasInterrupt().
set_fixobserver()
void fobs::set_fixobserver (FixObserver * o)
References obs.
Variable Documentation
obs
FixObserver* fobs::obs = NULL static
Referenced by get_fixobserver(), and set_fixobserver().
Please comment this page and report errors about it on the RefDocComments page.