DDD: SDED.h File Reference
SDED.h File Reference
#include <map>
#include "ddd/util/set.hh"
#include "ddd/DataSet.h"
#include "ddd/util/hash_support.hh"
Namespaces
namespace SDED
Functions
GSDD SDED::add (const d3::set< GSDD >::type &)
unsigned int SDED::statistics ()
void SDED::pstats (bool reinit=true)
size_t SDED::peak ()
void SDED::garbage ()
void square_union (std::map< GSDD, DataSet * > &res, const GSDD &s, DataSet *d)
Function Documentation
square_union()
void square_union (std::map< GSDD, DataSet * > & res, const GSDD & s, DataSet * d)
References DataSet::newcopy(), and DataSet::set_union().
Referenced by _SDED_Add::eval(), _SDED_Mult::eval(), _SDED_Minus::eval(), _SDED_Concat::eval(), sns::Mult::eval(), and _GShom::eval_skip().
Please comment this page and report errors about it on the RefDocComments page.