DDD: SDED.cpp File Reference
SDED.cpp File Reference
#include <set>
#include <map>
#include <typeinfo>
#include <cassert>
#include <iostream>
#include "ddd/util/configuration.hh"
#include "ddd/DataSet.h"
#include "ddd/DED.h"
#include "ddd/SDD.h"
#include "ddd/SDED.h"
#include "ddd/SHom.h"
#include "ddd/UniqueTable.h"
Classes
class _SDED
class _SDED_Add
class _SDED_Mult
class _SDED_Minus
class _SDED_Concat
Namespaces
namespace namespace_SDED
Typedefs
typedef UniqueTable< _SDED > SDEDtable
Functions
static GSDD compute (const _SDED &op)
void square_union (std::map< GSDD, DataSet * > &res, const GSDD &s, DataSet *d)
GSDD operator+ (const GSDD &g1, const GSDD &g2)
Operator for union of DDD.
GSDD operator* (const GSDD &g1, const GSDD &g2)
Operator for intersection of DDD.
GSDD operator^ (const GSDD &g1, const GSDD &g2)
Operator for concatenation of two SDD.
GSDD operator- (const GSDD &g1, const GSDD &g2)
Operator for set difference of DDD.
Variables
static SDEDtable uniqueSDED
static int namespace_SDED::Hits =0
static int namespace_SDED::Misses =0
static size_t namespace_SDED::Max_SDED =0
Typedef Documentation
SDEDtable
typedef UniqueTable<_SDED> SDEDtable
Function Documentation
compute()
static GSDD compute (const _SDED & op) static
References uniqueSDED.
Referenced by _SDED_Add::create(), _SDED_Add::create(), _SDED_Mult::create(), _SDED_Minus::create(), and _SDED_Concat::create().
operator*()
GSDD operator* (const GSDD & g1, const GSDD & g2)
Operator for intersection of DDD.
Semantics : d1 * d2 designates the intersection of the two sets
References _SDED_Mult::create().
operator+()
GSDD operator+ (const GSDD & g1, const GSDD & g2)
Operator for union of DDD.
Semantics : d1 + d2 produces the union d1 and d2
References _SDED_Add::create().
operator-()
GSDD operator- (const GSDD & g1, const GSDD & g2)
Operator for set difference of DDD.
Semantics : d1 - d2 contains elements in d1 and not in d2
References _SDED_Minus::create().
operator^()
GSDD operator^ (const GSDD & g1, const GSDD & g2)
Operator for concatenation of two SDD.
Semantics : d1 ^ d2 replaces "one" terminals of d1 by d2
References _SDED_Concat::create().
square_union()
void square_union (std::map< GSDD, DataSet * > & res, const GSDD & s, DataSet * d)
References DataSet::newcopy(), and DataSet::set_union().
Referenced by _SDED_Add::eval(), _SDED_Mult::eval(), _SDED_Minus::eval(), _SDED_Concat::eval(), sns::Mult::eval(), and _GShom::eval_skip().
Variable Documentation
uniqueSDED
SDEDtable uniqueSDED static
Referenced by compute(), SDED::garbage(), SDED::peak(), and SDED::statistics().
Please comment this page and report errors about it on the RefDocComments page.