
all:
	make -f  Makelib_d all
	make -f  Makelib_d cleanobj
	make -f  Makelib_o all
	make -f  Makelib_o cleanobj
	make -f  Makelib_i all
	make -f  Makelib_i cleanobj
	make -f  Makelib_p all
	make -f  Makelib_p cleanobj


clean:
	make -f  Makelib_d clean
	make -f  Makelib_o clean
	make -f  Makelib_p clean
	make -f  Makelib_i clean
















