name: Linux Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2.3.4
    - name: tag version date
      run: /bin/sh ./tag.sh
    - name: Install packages
      run: sudo apt-get install doxygen graphviz ;
    - name: autoreconf
      run: autoreconf -vfi
    - name: Prepare install folder
      run: mkdir usr && mkdir usr/local
    - name: configure
      run: ./configure --prefix=$PWD/usr/local/ || cat config.log
    - name: make lib
      run: cd ddd ; make -j ; cd ..
    - name: make demo
      run: make -j
    - name: make install
      run: make install
    - name: prepare artefact      
      run: tar cvzf ${{ runner.os }}.tgz usr/ ; mv ${{ runner.os }}.tgz website/
    - name: make dist
      run: make dist ;  mv ddd*.tar.gz website/ ;
    - name: make doc
      run: cd doc ; make ; cd .. ; mv doc/libddd.html/ website/ ;
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
          branch: ${{ runner.os }} # The branch the action should deploy to.
          folder: website/ # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch
          single-commit: true    
    - name: Trigger libITS
      uses: mvasigh/dispatch-action@main
      with:
          # You should create a personal access token and store it in your repository
          token: ${{ secrets.NOTIF_PAT }}
          repo: libITS
          owner: lip6
          event_type: ${{ runner.os }}
