name: OSX build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: macos-latest
    
    
    steps:
    - uses: actions/checkout@v2.3.4
    - name: tag version date
      run: /bin/sh ./tag.sh
    - name: Install packages
      run: brew install gcc autoconf automake libtool binutils ;
    - name: autoreconf
      run: autoreconf -vfi
    - name: Prepare install folder
      run: mkdir usr && mkdir usr/local
    - name: configure
      run: ./configure --prefix=$PWD/usr/local/ AR='gcc-ar-10' NM='gcc-nm-10' RANLIB='gcc-ranlib-10' CXX='g++-10' CC='gcc-10' || cat config.log
    - name: make lib
      run: cd ddd ; make -j ; cd ..
    - name: make demo
      run: make -j
    - name: make install
      run: make install
    - name: prepare artefact      
      run: tar cvzf ${{ runner.os }}.tgz usr/ ; mv ${{ runner.os }}.tgz website/
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ runner.os }} # The branch the action should deploy to.
          FOLDER: website/ # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch 
    - name: Trigger libITS
      uses: mvasigh/dispatch-action@main
      with:
          # You should create a personal access token and store it in your repository
          token: ${{ secrets.NOTIF_PAT }}
          repo: libITS
          owner: lip6
          event_type: ${{ runner.os }}
