name: OSX build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: macos-latest
    
    
    steps:
    - uses: actions/checkout@v2
    - name: tag version date
      run: /bin/sh ./tag.sh
    - name: Install packages
      run: brew install gcc autoconf automake libtool ;
    - name: autoreconf
      run: autoreconf -vfi
    - name: Prepare install folder
      run: mkdir usr && mkdir usr/local
    - name: configure
      run: ./configure --prefix=$PWD/usr/local/ --enable-nolto CXX='g++-10' CC='gcc-10' || cat config.log
    - name: make lib
      run: cd ddd ; make -j ; cd ..
    - name: make demo
      run: make -j
    - name: make install
      run: make install
    - name: prepare artefact      
      run: tar cvzf ${{ runner.os }}.tgz usr/ ; mv ${{ runner.os }}.tgz website/
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ runner.os }} # The branch the action should deploy to.
          FOLDER: website/ # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch 
