name: OSX build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: macos-latest
    
    
    steps:
    - uses: actions/checkout@v2.4.0
    - name: tag version date
      run: /bin/sh ./tag.sh
    - name: Install packages
      run: brew install gcc@9 autoconf automake libtool binutils ;
    - name: autoreconf
      run: autoreconf -vfi
    - name: Prepare install folder
      run: mkdir usr && mkdir usr/local
    - name: configure
      run: ./configure --prefix=$PWD/usr/local/ AR='gcc-ar-9' NM='gcc-nm-9' RANLIB='gcc-ranlib-9' CXX='g++-9' CC='gcc-9' || cat config.log
    - name: make lib
      run: cd ddd ; make -j ; cd ..
    - name: make demo
      run: make -j
    - name: make install
      run: make install
    - name: prepare artefact      
      run: rm usr/local/lib/libDDD_d* ; tar cvzf osx.tgz usr/ ; mv osx.tgz website/
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.8
      with:
          branch: osx  # The branch the action should deploy to.
          folder: website/  # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch
          single-commit: true 
    - name: Trigger libITS
      uses: mvasigh/dispatch-action@main
      with:
          # You should create a personal access token and store it in your repository
          token: ${{ secrets.NOTIF_PAT }}
          repo: libITS
          owner: lip6
          event_type: ${{ runner.os }}
