name: windows build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: add msys to path
      run: set 'PATH=%PATH%;C:\msys64\mingw64\bin;C:\msys64\usr\bin;C:\mingw64\bin'
    - name: install path
      run: C:\msys64\usr\bin\bash -lc "echo 'export PATH="/mingw64/bin:$PATH"' >> ~/.bashrc"
    - name: test path
      run: C:\msys64\usr\bin\bash -lc "which autoconf ; which ls ; which g++"
    - name: install gcc
      run: C:\msys64\usr\bin\bash -lc "PATH=\"/mingw64/bin:$PATH\" ; export PATH ; which autoconf ; which ls ; which g++; pacman -Qe ; pacman -Syuu --noconfirm ; pacman --noconfirm -Sy mingw-w64-x86_64-gcc ; which g++ ; g++ --version"
    - name: install gcc
      run: C:\msys64\usr\bin\bash -lc "pacman -Syuu ; g++ --version"
    - name: test it
      run: rsync --help
    - name: Grab rsync on windows
      run: curl.exe -o cwsync.zip https://itefix.net/dl/free-software/cwrsync_6.2.1_x64_free.zip ; tar.exe -x -f cwsync.zip ; move bin\* C:\Program Files\Git\bin\ ; rsync --help
    - name: test setup
      run:  C:\msys64\usr\bin\bash -lc "ls ; pwd ; cd /D/a/libDDD/libDDD ; pwd ; ls ; env"
    - name: configure and make
      run:  C:\msys64\usr\bin\bash -lc "export PATH=$PATH:/mingw64/bin ; cd /D/a/libDDD/libDDD ; autoreconf -vfi && ./configure --prefix=/D/a/libDDD/libDDD/usr/local/ --enable-nolto --enable-mingw-native && make && make install || cat config.log"
    - name: package zip
      run:  C:\msys64\usr\bin\bash -lc "cd /D/a/libDDD/libDDD ; tar -a -c -f windows.zip usr/ ; mv windows.zip website/"
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ runner.os }} # The branch the action should deploy to.
          FOLDER: website/ # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch 
