name: windows build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: print path
      run: $Env:Path
    - name: add msys to powershell path
      run: $oldpath = (Get-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' -Name PATH).path ; $newpath = "$oldpath;C:\msys64\mingw64\bin;C:\msys64\usr\bin;C:\mingw64\bin" ; Set-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' -Name PATH -Value $newpath
    - name: add msys to env
      run: $ENV:PATH="$ENV:PATH;C:\msys64\mingw64\bin;C:\msys64\usr\bin;C:\mingw64\bin"
    - name: non official add path
      run: echo "##[add-path]C:\msys64\mingw64\bin;C:\msys64\usr\bin;C:\mingw64\bin"       
    - name: add msys to env by gh action
      run: echo "C:\msys64\usr\bin" >> $GITHUB_PATH
    - name: print path 2
      run: $Env:Path
    - name: print path 3
      run: echo "$PATH"
    - name: install rsync
      run: C:\msys64\usr\bin\bash -lc "pacman -S --noconfirm rsync ; which rsync ; cp /usr/bin/rsync /usr/bin/rsync.exe"
    - name: test setup powershell
      run:  where rsync ; rsync --help 
    - name: test setup
      run:  C:\msys64\usr\bin\bash -lc "ls ; pwd ; cd /D/a/libDDD/libDDD ; pwd ; ls ; env"
    - name: configure and make
      run:  C:\msys64\usr\bin\bash -lc "PATH+=:/mingw64/bin ; cd /D/a/libDDD/libDDD ; autoreconf -vfi && ./configure --prefix=/D/a/libDDD/libDDD/usr/local/ --enable-nolto --enable-mingw-native && make -j && make install || cat config.log"
    - name: package zip
      run:  C:\msys64\usr\bin\bash -lc "cd /D/a/libDDD/libDDD ; tar -a -c -f windows.zip usr/ ; mv windows.zip website/"
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ runner.os }} # The branch the action should deploy to.
          FOLDER: website/ # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch 
